# 14절. 연습문제 실습형

In [1]:
from seaborn import load_dataset
iris = load_dataset('iris')
type(iris)

pandas.core.frame.DataFrame

In [2]:
# 1. 처음 다섯개 행만 출력
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
# 2. iris 데이터를 독립변수 X와 종속변수 y로 나누세요. 종속변수는 species. X, y모두 데이터프레임
y = iris[['species']]
X = iris.drop(columns=['species'])
print(y.shape, X.shape)
X

(150, 1) (150, 4)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# 3. iris 데이터에서 처음 50개행을 빼네서 temp 변수에 저장하세요
temp = iris[:50]
temp.tail()

In [ ]:
# 4. 3번에서 선택한 데이터 프레임의 요약정보를 출력하세요. 모든 열에 대해 요약정보가 출력
temp.info()

In [ ]:
# 5. versicolor종의 데이터만 iris_versicolor변수에 저장하세요
iris_versicolor = iris.loc[iris['species'] == 'versicolor']
iris_versicolor.sample(5)

In [ ]:
# 6. 2번의 x와 y변수를 합해서 iris_df 데이터 프레임으로 만드세요
import pandas as pd
iris_df = pd.concat([X, y], axis=1)
iris_df.head()

In [ ]:
# 7. iris 열평균
iris_mean2 = iris.mean(axis=1, numeric_only=True)
iris_mean2

In [ ]:
# 8. iris 열들 사이의 상관계수
iris_mean2 = iris.corr(numeric_only=True)
iris_mean2

In [ ]:
# 9. 변수별 평균차이를 출력
iris_mean = iris.iloc[:, :-1].mean(axis=0)
iris_diff = iris.iloc[:, :-1].sub(iris_mean, axis=1)
display(iris_diff.head())

In [ ]:
# 10. 종별 평균
species_mean = iris.groupby('species').mean()
species_mean

In [ ]:
# 11. 각 요소들과 종별 변수의 평균과의 차이를 각 종별로 3개씩 출력