In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font color = "red" size = "5">ch14. 웹데이터 수집</font></b>
# 1절. BeautifulSoup
- pip install bs4
- 아나콘다를 설치하면 7500여개의 패키지 자동 설치됨
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests # HTTP 요청 처리 lib
from requests_file import FileAdapter

In [3]:
s = requests.Session() # HTTP 요청 관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get('file:///ai_x/source/01_python/data/ch14_sample.html')
response

In [4]:
response.status_code
# 200 : 정상
# 404 : 없는 페이지
# 406 : get, post 오류
# 500 : python 문법 error

200

In [5]:
# 바이너리 형식의 내용
response.content

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [6]:
response.content.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [7]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [8]:
# html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, # response.text = response.content
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

#### 첫번째함수 soup.select_one('선택자') : 해당 선택자 처음 하나만 가져옴
- select_one(선택자)와 find(태그, 속성)

In [9]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만 가져옴
el = soup.select_one('h1')
print('el : ', el)
print('el.text : ', el.text)
print('el.string : ', el.string)
print('el의 속성들 : ', el.attrs)
print('el의 title속성', el.attrs['title'])
print('el의 title속성', el.attrs.get('title'))
print('el의 이름 : ', el.name)

el :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
el.text :  Hello, CSS
el.string :  Hello, CSS
el의 속성들 :  {'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}
el의 title속성 greeting
el의 title속성 greeting
el의 이름 :  h1

#### 두번째함수 soup.select('선택자') : 해당 선택자 모든 엘리먼트를 리스트로 가져옴

In [10]:
# soup.select('선택자') : 해당 선택자 모든 엘리먼트를 리스트로 가져옴
el = soup.select('h1')
print('리스트 el : ', el)
print('el의 text들 : ', [e.text for e in el])
#for e in el:
#    print(e.text, end=',')
print('el의 속성들 : ', [e.attrs for e in el])
print('el의 class속성들 : ', [e.attrs.get('class') for e in el])

리스트 el :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el의 text들 :  ['Hello, CSS', 'Hi, CSS']
el의 속성들 :  [{'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}, {'class': ['css']}]
el의 class속성들 :  [['greeting', 'css'], ['css']]

#### 세번째함수 find(태그, 속성)

In [11]:
# select_one(선택자)와 find(태그, 속성)
print('select_one : ', soup.select_one('h1.css'))
print('find : ', soup.find('h1', {'class':'css'}))
print('find : ', soup.find('h1', class_='css'))
print('select_one : ', soup.select_one('h1#text'))
print('find : ', soup.find('h1',{'id':'text'}))
print()
print('select')

select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select

#### 네번쨰함수 find_all(태그,속성)

In [12]:
# select(선택자)와 find_all(태그, 속성)
print('모든 h1.css, span 태그(select) : ', soup.select('h1.css, span'))
print('모든 h1.css, span태그(find_all) : ', soup.find_all(['h1','span'], class_='css'))
print() # 개행

모든 h1.css, span 태그(select) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css, span태그(find_all) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

#### 없는 엘리먼트 찾기

In [13]:
# 없는 엘리먼트 찾기
print('find_all(빈리스트) : ', soup.find_all('a', class_='css'))
print('find(None) : ', soup.find('a', class_='css'))
print('select(빈리스트) : ', soup.select('a.css'))
print('select_one(None) : ', soup.select_one('a.css'))

find_all(빈리스트) :  []
find(None) :  None
select(빈리스트) :  []
select_one(None) :  None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
#### json, xml, html
## 2.1 JSON파일
#### requests모듈(get)
#### urllib.request모듈(urlopen)
#### 크롤링 허용 범위는 사이트마다 ~.com/robots.txt에서 확인할 수 있습니다

In [14]:
# 크롤링 허용 범위는 사이트마다 ~.com/robots.txt에서 확인할 수 있습니다

#### 방법1 import requests

In [15]:
# 방법1 
import requests
response = requests.get('https://api.github.com')
response, response.status_code

(<Response [200]>, 200)

#### 방법2 urillib.request모듈(urlopen)

In [16]:
# 방법2
from urllib.request import urlopen
response = urlopen('https://api.github.com')
response

In [17]:
text = '{"속성1":"값1", "속성2":"값2"}'
type(text)

str

In [18]:
# 문자(딕셔너리 타입)를 딕셔너리
#'{"속성1":"값1", "속성2":"값2"}' => {"속성1":"값1", "속성2":"값2"}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2'}

## 2.2 html 파일
### 1) 환율정보 가져오기(네이버->증권->시장지표)
- https://finance.naver.com/marketindex/

#### 방법1 requests모듈

In [19]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
#response, response.status_code
#response.content
#response.content.decode('cp949')
#response.text
soup = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

#### 방법2 from urllib.request import urlopen

In [20]:
# 방법2 from urllib.request import urlopen
from urllib.request import urlopen
response = urlopen(url)
#response.status
#response.read().decode('cp949')
soup = BeautifulSoup(response, # response.read()
                     'html.parser')

In [21]:
title = soup.select('h3.h_lst > span.blind')
for t in title:
    print(t.text, end='\t')

미국 USD	일본 JPY(100엔)	유럽연합 EUR	중국 CNY	달러/일본 엔	유로/달러	영국 파운드/달러	달러인덱스	WTI	휘발유	국제 금	국내 금

In [22]:
price = soup.select('div.head_info > span.value')
[p.text for p in price]
[round(float(p.text.replace(',',''))) for p in price]
[round(float(''.join(p.text.split(',')))) for p in price]

[1372, 952, 1553, 191, 144, 1, 1, 99, 61, 1633, 3300, 146093]

In [23]:
out = '1,375.20'
round(float(''.join(out.split(','))))

1375

In [24]:
round(float(out.replace(',','')))

1375

In [25]:
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7, '') # 7번째 index에 '' 추가
unit

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [26]:
status = soup.select('div.head_info > span.blind')
[t.text for t in title]
[p.text for p in price]
unit
[s.string for s in status]

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '상승']

In [27]:
len(title), len(price), len(unit), len(status)

(12, 12, 12, 12)

In [28]:
for idx in range(len(title)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                  title[idx].text,
                                 price[idx].text,
                                 unit[idx],
                                 status[idx].text))

1. 미국 USD : 1,372.10원 - 하락
2. 일본 JPY(100엔) : 952.02원 - 하락
3. 유럽연합 EUR : 1,553.01원 - 하락
4. 중국 CNY : 190.89원 - 하락
5. 달러/일본 엔 : 144.3800엔 - 상승
6. 유로/달러 : 1.1342달러 - 하락
7. 영국 파운드/달러 : 1.3520달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.96원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 146093.27원 - 상승

In [29]:
for t, p, u, s in zip(title, price, unit, status):
    print("{} : {}{} - {}".format(t.text,
                                 p.text,
                                 u,
                                 s.text))

미국 USD : 1,372.10원 - 하락
일본 JPY(100엔) : 952.02원 - 하락
유럽연합 EUR : 1,553.01원 - 하락
중국 CNY : 190.89원 - 하락
달러/일본 엔 : 144.3800엔 - 상승
유로/달러 : 1.1342달러 - 하락
영국 파운드/달러 : 1.3520달러 - 하락
달러인덱스 : 99.4200 - 상승
WTI : 60.89달러 - 하락
휘발유 : 1632.96원 - 하락
국제 금 : 3300.4달러 - 하락
국내 금 : 146093.27원 - 상승

In [30]:
for idx, (t, p, u, s) in enumerate(zip(title, price, unit, status)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                      t.text,
                                 p.text,
                                 u,
                                 s.text))

1. 미국 USD : 1,372.10원 - 하락
2. 일본 JPY(100엔) : 952.02원 - 하락
3. 유럽연합 EUR : 1,553.01원 - 하락
4. 중국 CNY : 190.89원 - 하락
5. 달러/일본 엔 : 144.3800엔 - 상승
6. 유로/달러 : 1.1342달러 - 하락
7. 영국 파운드/달러 : 1.3520달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.96원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 146093.27원 - 상승

### 2) 이번주 로또번호 출력
- google에 "로또번호 당첨번호" 검색
https://dhlottery.co.kr/gameResult.do?method=byWin
```
1173회 당첨결과
(2025년 05월 24일 추첨)
당첨번호 [1,5,18,20,30,35]
보너스 3
```

In [31]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

In [32]:
# 방법2 urlopen
from urllib.request import urlopen
response = urlopen(url)
soup = BeautifulSoup(response, "html.parser")

In [33]:
times = soup.select_one('div.win_result > h4 > strong').text
date = soup.select_one('div.win_result > p.desc').text
title1 = soup.select_one('div.num.win>strong').text
lotto_number = soup.select('div.num.win>p>span')
title2 = soup.select_one('div.num.bonus>strong').string
bonus_number = soup.select_one('div.num.bonus > p > span').text
print( times, date, title1, [int(lotto.text) for lotto in lotto_number]
     , title2, bonus_number)

# for t in times:
#     print(t.text, end='\t')

1173회 (2025년 05월 24일 추첨) 당첨번호 [1, 5, 18, 20, 30, 35] 보너스 3

In [34]:
# 위의 select 함수를 find함수로
# times = soup.select_one('div.win_result > h4 > strong').text
win_result = soup.find('div', class_="win_result")
times = win_result.find('strong').text

# date = soup.select_one('div.win_result > p.desc').text
date = soup.find('p', class_='desc').text

print(times, date)

# title1 = soup.select_one('div.num.win>strong').text
num_win = soup.find('div', class_=['win'])
title1 = num_win.find('strong').text

# lotto_number = soup.select('div.num.win>p>span')
lotto_number = num_win.find_all('span') # 배열

print(title1, [int(lotto.text) for lotto in lotto_number])

# title2 = soup.select_one('div.num.bonus>strong').string
num_bonus = soup.find('div', class_=['bonus'])
title2 = num_bonus.find('strong').text

print(num_bonus)

# bonus_number = soup.select_one('div.num.bonus > p > span').text
bonus_number = num_bonus.find('span').text

print( times, date, title1, [int(lotto.text) for lotto in lotto_number]
     , title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
<div class="num bonus">
<strong>보너스</strong>
<p><span class="ball_645 lrg ball1">3</span></p>
</div>
1173회 (2025년 05월 24일 추첨) 당첨번호 [1, 5, 18, 20, 30, 35] 보너스 3

### 3) 다음 검색 리스트
```
no             title                     link
0   [비트코인 2025] 백악관 크립토 차르~      https://v.daum.net/v/20250528103907230
1   [비즈 나우] 비트코인 2025 컨퍼런스 개막~  https://v.daum.net/v/20250528075215864
...
```

#### 방법1

In [35]:
# 방법1
import requests
from bs4 import BeautifulSoup

word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
print(url)
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no':idx,
                           'title':item.text,
                           'link':item.attrs['href']})
import pandas as pd
pd.DataFrame(items_find_list)

https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8비트코인

,no,title,link
0,0,EU관세 발언 후 10만8000달러선 회복 비트코인…파키스탄 ‘비트코인 채굴’ 전...,http://v.daum.net/v/20250526080440640
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
3,3,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
4,4,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
5,5,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
6,6,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
7,7,"10만 달러, 11만 달러… 트럼프 관세 변덕에 비트코인 '출렁'",http://v.daum.net/v/20250527132843430
8,8,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
9,9,'해킹 산업화'의 원흉 '비트코인'…위치추적 안 되자 활개[은폐⑥],http://v.daum.net/v/20250527090029503

In [36]:
import requests
from bs4 import BeautifulSoup

word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
print(url)
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 2차원 리스트

items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')

for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
items_find_list
import pandas as pd
pd.DataFrame(items_find_list, columns=['no', 'title', 'link'])

https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8비트코인

,no,title,link
0,0,EU관세 발언 후 10만8000달러선 회복 비트코인…파키스탄 ‘비트코인 채굴’ 전...,http://v.daum.net/v/20250526080440640
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
3,3,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
4,4,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
5,5,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
6,6,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
7,7,"10만 달러, 11만 달러… 트럼프 관세 변덕에 비트코인 '출렁'",http://v.daum.net/v/20250527132843430
8,8,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
9,9,'해킹 산업화'의 원흉 '비트코인'…위치추적 안 되자 활개[은폐⑥],http://v.daum.net/v/20250527090029503

#### 다음 뉴스 검색(키워드, 원하는 페이지수)

In [37]:
# 다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

keyword = '비트코인'
page = 2
# url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={page}'
url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
params = {'q':keyword,
          'p':page}

response = requests.get(url, params=params)

#
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
#     print({'no': (page-1)*10 + idx,
#                            'title':item.text,
#                            'link':item.attrs['href']})

In [38]:
# 함수만들기
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword,
          'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
    items_find_list = [] # 검색결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
    return items_find_list

In [39]:
collect_list('비트코인', 2)

[{'no': 10,
  'title': ' [대선공약] 가상자산 현물 ETF·토큰증권 확산 공감대…코인 육성 빨라진다 ',
  'link': 'http://v.daum.net/v/20250528174700772'},
 {'no': 11,
  'title': " 숨 고르는 비트코인, 10만8000달러선 '주춤' ",
  'link': 'http://v.daum.net/v/20250528095921258'},
 {'no': 12,
  'title': ' “맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터] ',
  'link': 'http://v.daum.net/v/20250528143002735'},
 {'no': 13,
  'title': ' 연일 최고가 경신하는 비트코인…투자자들 강 건너 불구경하는 이유는 ',
  'link': 'http://v.daum.net/v/20250526212400275'},
 {'no': 14,
  'title': ' "비트코인 산다"…트럼프家, 25억달러 자금 조달 추진[코인브리핑] ',
  'link': 'http://v.daum.net/v/20250528111837527'},
 {'no': 15,
  'title': ' [김대호 박사의 오늘의 키워드] 소비자신뢰지수·비트코인 2025·머스크 한마디·애플 괘씸죄 ',
  'link': 'http://v.daum.net/v/20250528071325361'},
 {'no': 16,
  'title': ' [포토]라스베이거스에서 열린 2025 비트코인 콘퍼런스 ',
  'link': 'http://v.daum.net/v/20250528155536962'},
 {'no': 17,
  'title': ' 비트코인과 엇갈리는 이더리움·리플, 왜? ',
  'link': 'http://v.daum.net/v/20250526164319028'},
 {'no': 18,
  'title': " 대주주 먹튀 근절·상법개정…'코스피 5000' 뒷받침 공약 발표 ",
  'link': 'http://v.daum.net/v/20250528164529582'},
 {'no': 19,
  'title': ' <단독>"예배 참석하면 코인 드려요. 5년 안에 비트코인 넘어섭니다"..신앙심 노린 코인 유사 사기 기승 ',
  'link': 'http://v.daum.net/v/20250528083323774'}]

#### 원하는 keyword로 다음검색

In [40]:
# 원하는 keyword로 다음검색
result = []
keyword = "청바지"
pages = 4
for page in range(1, pages+1):
    result.extend(collect_list(keyword, page))
    time.sleep(3)
result_df = pd.DataFrame(result)
result_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [41]:
keywords = ['청바지','면바지']
pages = 2

result0 = [] # 청바지 검색결과 20개
result1 = [] # 면바지 검색결과 20개

for i, keyword in enumerate(keywords):
    print(f'...loading... {i}번째 {keyword} 검색중입니다.')
    for page in range(1, pages+1):
#         print(f'...loading... {i}번째 {keyword} {page} 검색중입니다.')
        if i == 0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(1)

...loading... 0번째 청바지 검색중입니다.
...loading... 1번째 면바지 검색중입니다.

In [42]:
result0_df = pd.DataFrame(result0)
result0_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [43]:
result1_df = pd.DataFrame(result1)
result1_df.head()

,no,title,link
0,0,사천에서 쾌청한 날씨 속 탁 트인 남해 풍경 즐겨요!,http://v.daum.net/v/20250528104429529
1,1,"윤승아, ♥김무열 쏙 빼닮은 깜찍 子 하객룩 공개‥벌써 우월한 유전자",http://v.daum.net/v/20250526145941690
2,2,"이번 주 포천 여행,반팔 하나로 충분할까?",http://v.daum.net/v/20250527171732518
3,3,"이재명, 첫 대학 방문…이준석 겨냥?",http://v.daum.net/v/20250526191942751
4,4,"""나는 젊어"" 팔소매 접은 이준석의 '흰셔츠' 속에도 뼈가 담겼다[21대 대선 리...",http://v.daum.net/v/20250525070013619

In [44]:
collect_list("청바지", 1)

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

In [45]:
result0_df.to_csv('data/ch14_'+keyword[0]+'.csv', index=False, encoding='cp949')
result1_df.to_csv('data/ch14_'+keyword[1]+'.csv', index=False, encoding='utf-8')

### 4) User-Agent를 추가하여 크롤링
- urlopen()함수를 사용하면 크롤링이 안되는 사이트
- User-Agent를 추가하여 크롤링

In [46]:
# 방법2 : urlopen()함수를 사용하면 크롤링이 안되는 사이트
# robots.txt에 Disallow로 되어 있는 경우
from urllib.request import urlopen, Request
import urllib.parse
word = '비트코인'
word = urllib.parse.quote(word)
print(word)
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
# User-Agent를 추가하여 브라우저처럼 보이게 포장
headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
response = urlopen(request)
soup = BeautifulSoup(response, # response.content
                    "html.parser")

def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword,
          'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
    items_find_list = [] # 검색결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
    return items_find_list

collect_list("청바지", 1)

%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

### 꼭 User-Agent를 사용하여야 하는 경우 : https://www.melon.com/chart/

In [47]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'

melonpage = requests.get(url)
melonpage

In [48]:
# 방법2
from urllib.request import urlopen, Request
# 에러남
# melonpage = urlopen(url)
# melonpage

#### 멜론 100차트 연습

In [49]:
# User-Agent 추가
headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
# 방법2
request = Request(url, headers=headers)
melonpage = urlopen(request)

# 방법1
melonpage = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, # melonpage.content
                    "html.parser")
# soup

In [51]:
# 멜론 순위, 노래 제목, 가수, 좋아요
rank1 = [r.text for r in soup.select('div.wrap.t_center > span.rank')][1:]
title1 = [t.text for t in soup.select('div.wrap_song_info > div.ellipsis.rank01 > span > a')]
singer1 = [s.text for s in soup.select('div.wrap_song_info > div.ellipsis.rank02 > a')]
print(rank1, title1, singer1)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100'] ['너에게 닿기를', 'Never Ending Story', 'Drowning', 'like JENNIE', '모르시나요(PROD.로코베리)', 'THUNDER', 'TOO BAD (feat. Anderson .Paak)', '네모의 꿈', 'Whiplash', 'HOME SWEET HOME (feat. 태양, 대성)', '나는 반딧불', '어제보다 슬픈 오늘', '오늘만 I LOVE YOU', 'REBEL HEART', 'HAPPY', '빨간 운동화', 'Flower', 'APT.', '청춘만화', 'HOT', '10월 4일', '한 페이지가 될 수 있게', 'Last Scene (Feat. 원슈타인)', 'HBD', 'MY LOVE(2025)', '그날이 오면', '내게 사랑이 뭐냐고 물어본다면', 'Fly Up', 'Welcome to the Show', '소나기', '천상연', 'Die With A Smile', 'toxic till the end', 'HANDS UP', 'Supernova', '예뻤어', 'Skyfall (THE 8 Solo)', 'ATTITUDE', 'I DO ME', '미치게 그리워서', '미인 (Feat. Balming Tiger)', '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'DRIP', 'Love wins all', 'PO￦ER', '청혼하지 않을 이유를 못 찾았어', '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))', '사랑은 늘 도망가', 'Bad Influence (Prod. by Pharrell Williams)', '내 이름 맑음', '99.9% (WONWOO Solo)', '슬픈 초대장', '첫 만남은 계획대로 되지 않아', 'Fortunate Change (JOSHUA Solo)', 'Raindrops (SEUNGKWAN Solo)', 'UP (KARINA Solo)', '고민중독', '나는 아픈 건 딱 질색이니까', '주저하는 연인들을 위해', 'TAKE ME', '너의 모든 순간', '운명 (WOOZI Solo)', 'Damage (HOSHI Solo) (feat. Timbaland)', 'Happy Virus (DK Solo)', 'Magnetic', 'How Sweet', '사랑인가 봐', 'I Feel Good', '에피소드', '비의 랩소디', 'Shake It Off (MINGYU Solo)', '우연 (JEONGHAN Solo)', 'Bag Bad Back', '123-78', '모든 날, 모든 순간 (Every day, Every Moment)', 'The Chase', '시작의 아이', 'Supersonic', 'Jungle (S.COUPS Solo)', '쌍둥이자리 (Gemini) (JUN Solo)', 'I AM', 'Shining Star (Vernon Solo)', 'Hype Boy', '다정히 내 이름을 부르면', 'Seven (feat. Latto) - Clean Ver.', '헤어지자 말해요', 'Trigger (DINO Solo)', '영원해', '이렇게 좋아해 본 적이 없어요', '우리들의 블루스', '봄날', '무제(無題) (Untitled, 2014)', '천국보다 아름다운', '인사', '굿데이 2025 (텔레파시 + 달빛 창가에서)', 'Sticky', 'Small girl (feat. 도경수(D.O.))', 'Dash', '사막에서 꽃을 피우듯', '다시 만날 수 있을까'] ['10CM', '아이유', 'WOODZ', '제니 (JENNIE)', '조째즈', '세븐틴 (SEVENTEEN)', 'G-DRAGON', '아이유', 'aespa', 'G-DRAGON', '황가람', '우디 (Woody)', 'BOYNEXTDOOR', 'IVE (아이브)', 'DAY6 (데이식스)', '아이유', '오반(OVAN)', '로제 (ROSÉ)', 'Bruno Mars', '이무진', 'LE SSERAFIM (르세라핌)', '아이유', 'DAY6 (데이식스)', '아이유', '세븐틴 (SEVENTEEN)', '이예은', '아샤트리', '전건호', '투모로우바이투게더', '로이킴', 'RIIZE', 'DAY6 (데이식스)', '이클립스 (ECLIPSE)', '이창섭', 'Lady Gaga', 'Bruno Mars', '로제 (ROSÉ)', 'MEOVV (미야오)', 'aespa', 'DAY6 (데이식스)', '세븐틴 (SEVENTEEN)', 'IVE (아이브)', 'KiiiKiii (키키)', '황가람', '아이유', 'AKMU (악뮤)', 'BABYMONSTER', '아이유', 'G-DRAGON', '이무진', '너드커넥션 (Nerd Connection)', '임영웅', '세븐틴 (SEVENTEEN)', 'QWER', '세븐틴 (SEVENTEEN)', '순순희(지환)', 'TWS (투어스)', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'aespa', 'QWER', 'i-dle (아이들)', '잔나비', 'G-DRAGON', '성시경', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', '아일릿(ILLIT)', 'NewJeans', '멜로망스', 'BOYNEXTDOOR', '이무진', '임재현', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'RIIZE', 'BOYNEXTDOOR', '폴킴', 'Hearts2Hearts (하츠투하츠)', '마크툽 (MAKTUB)', '프로미스나인', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'IVE (아이브)', '세븐틴 (SEVENTEEN)', 'NewJeans', '경서예지', '전건호', '정국', '박재정', '세븐틴 (SEVENTEEN)', '도경수(D.O.)', 'BOYNEXTDOOR', '임영웅', '방탄소년단', 'G-DRAGON', '임영웅', '범진', 'G-DRAGON', '황정민', '데프콘', '홍진경', '정형돈', '조세호', '기안84', '안성재', '태양', '정해인', '황광희', '임시완', '이수혁', '대성', '코드 쿤스트 (CODE KUNST)', 'CL', '김고은', 'DAY6 (데이식스)', '부석순 (SEVENTEEN)', 'aespa', 'KISS OF LIFE', '이영지', 'PLAVE', '우디 (Woody)', '임영웅']

In [53]:
result = []
for idx in range(len(title1)):
    rank = rank1[idx]
    title2 = title1[idx]
    singer = singer1[idx]
    print(f"{rank} : {title2} - {singer}")    
    result.append([idx + 1, rank, title2, singer])

1 : 너에게 닿기를 - 10CM
2 : Never Ending Story - 아이유
3 : Drowning - WOODZ
4 : like JENNIE - 제니 (JENNIE)
5 : 모르시나요(PROD.로코베리) - 조째즈
6 : THUNDER - 세븐틴 (SEVENTEEN)
7 : TOO BAD (feat. Anderson .Paak) - G-DRAGON
8 : 네모의 꿈 - 아이유
9 : Whiplash - aespa
10 : HOME SWEET HOME (feat. 태양, 대성) - G-DRAGON
11 : 나는 반딧불 - 황가람
12 : 어제보다 슬픈 오늘 - 우디 (Woody)
13 : 오늘만 I LOVE YOU - BOYNEXTDOOR
14 : REBEL HEART - IVE (아이브)
15 : HAPPY - DAY6 (데이식스)
16 : 빨간 운동화 - 아이유
17 : Flower - 오반(OVAN)
18 : APT. - 로제 (ROSÉ)
19 : 청춘만화 - Bruno Mars
20 : HOT - 이무진
21 : 10월 4일 - LE SSERAFIM (르세라핌)
22 : 한 페이지가 될 수 있게 - 아이유
23 : Last Scene (Feat. 원슈타인) - DAY6 (데이식스)
24 : HBD - 아이유
25 : MY LOVE(2025) - 세븐틴 (SEVENTEEN)
26 : 그날이 오면 - 이예은
27 : 내게 사랑이 뭐냐고 물어본다면 - 아샤트리
28 : Fly Up - 전건호
29 : Welcome to the Show - 투모로우바이투게더
30 : 소나기 - 로이킴
31 : 천상연 - RIIZE
32 : Die With A Smile - DAY6 (데이식스)
33 : toxic till the end - 이클립스 (ECLIPSE)
34 : HANDS UP - 이창섭
35 : Supernova - Lady Gaga
36 : 예뻤어 - Bruno Mars
37 : Skyfall (THE 8 Solo) - 로제 (ROSÉ)
38 : ATTITUDE - MEOVV (미야오)
39 : I DO ME - aespa
40 : 미치게 그리워서 - DAY6 (데이식스)
41 : 미인 (Feat. Balming Tiger) - 세븐틴 (SEVENTEEN)
42 : 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 - IVE (아이브)
43 : DRIP - KiiiKiii (키키)
44 : Love wins all - 황가람
45 : PO￦ER - 아이유
46 : 청혼하지 않을 이유를 못 찾았어 - AKMU (악뮤)
47 : 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) - BABYMONSTER
48 : 사랑은 늘 도망가 - 아이유
49 : Bad Influence (Prod. by Pharrell Williams) - G-DRAGON
50 : 내 이름 맑음 - 이무진
51 : 99.9% (WONWOO Solo) - 너드커넥션 (Nerd Connection)
52 : 슬픈 초대장 - 임영웅
53 : 첫 만남은 계획대로 되지 않아 - 세븐틴 (SEVENTEEN)
54 : Fortunate Change (JOSHUA Solo) - QWER
55 : Raindrops (SEUNGKWAN Solo) - 세븐틴 (SEVENTEEN)
56 : UP (KARINA Solo) - 순순희(지환)
57 : 고민중독 - TWS (투어스)
58 : 나는 아픈 건 딱 질색이니까 - 세븐틴 (SEVENTEEN)
59 : 주저하는 연인들을 위해 - 세븐틴 (SEVENTEEN)
60 : TAKE ME - aespa
61 : 너의 모든 순간 - QWER
62 : 운명 (WOOZI Solo) - i-dle (아이들)
63 : Damage (HOSHI Solo) (feat. Timbaland) - 잔나비
64 : Happy Virus (DK Solo) - G-DRAGON
65 : Magnetic - 성시경
66 : How Sweet - 세븐틴 (SEVENTEEN)
67 : 사랑인가 봐 - 세븐틴 (SEVENTEEN)
68 : I Feel Good - 세븐틴 (SEVENTEEN)
69 : 에피소드 - 아일릿(ILLIT)
70 : 비의 랩소디 - NewJeans
71 : Shake It Off (MINGYU Solo) - 멜로망스
72 : 우연 (JEONGHAN Solo) - BOYNEXTDOOR
73 : Bag Bad Back - 이무진
74 : 123-78 - 임재현
75 : 모든 날, 모든 순간 (Every day, Every Moment) - 세븐틴 (SEVENTEEN)
76 : The Chase - 세븐틴 (SEVENTEEN)
77 : 시작의 아이 - RIIZE
78 : Supersonic - BOYNEXTDOOR
79 : Jungle (S.COUPS Solo) - 폴킴
80 : 쌍둥이자리 (Gemini) (JUN Solo) - Hearts2Hearts (하츠투하츠)
81 : I AM - 마크툽 (MAKTUB)
82 : Shining Star (Vernon Solo) - 프로미스나인
83 : Hype Boy - 세븐틴 (SEVENTEEN)
84 : 다정히 내 이름을 부르면 - 세븐틴 (SEVENTEEN)
85 : Seven (feat. Latto) - Clean Ver. - IVE (아이브)
86 : 헤어지자 말해요 - 세븐틴 (SEVENTEEN)
87 : Trigger (DINO Solo) - NewJeans
88 : 영원해 - 경서예지
89 : 이렇게 좋아해 본 적이 없어요 - 전건호
90 : 우리들의 블루스 - 정국
91 : 봄날 - 박재정
92 : 무제(無題) (Untitled, 2014) - 세븐틴 (SEVENTEEN)
93 : 천국보다 아름다운 - 도경수(D.O.)
94 : 인사 - BOYNEXTDOOR
95 : 굿데이 2025 (텔레파시 + 달빛 창가에서) - 임영웅
96 : Sticky - 방탄소년단
97 : Small girl (feat. 도경수(D.O.)) - G-DRAGON
98 : Dash - 임영웅
99 : 사막에서 꽃을 피우듯 - 범진
100 : 다시 만날 수 있을까 - G-DRAGON

In [64]:
import pandas as pd
parsed_result = [[item[2], item[3]] for item in result]

df = pd.DataFrame(parsed_result, columns=['title', 'singer'], index=range(1, len(parsed_result) + 1))
df

                            title       singer
1                         너에게 닿기를         10CM
2              Never Ending Story          아이유
3                        Drowning        WOODZ
4                     like JENNIE  제니 (JENNIE)
5                모르시나요(PROD.로코베리)          조째즈
..                            ...          ...
96                         Sticky        방탄소년단
97   Small girl (feat. 도경수(D.O.))     G-DRAGON
98                           Dash          임영웅
99                    사막에서 꽃을 피우듯           범진
100                   다시 만날 수 있을까     G-DRAGON

[100 rows x 2 columns]

#### 멜론 100차트 연습 선생님ver

In [61]:
title_els = soup.select('div.ellipsis.rank01 > span')
singer_els = soup.select('div.ellipsis.rank02 > span.checkEllipsis')
len([title.text.strip() for title in title_els]), \
len([singer.text for singer in singer_els])
for idx, (title, singer) in enumerate(zip(title_els, singer_els)):
    print('{}위 | {} - {}'.format(idx+1,
                                 title.text.strip(),
                                 singer.text))

1위 | 너에게 닿기를 - 10CM
2위 | Never Ending Story - 아이유
3위 | Drowning - WOODZ
4위 | like JENNIE - 제니 (JENNIE)
5위 | 모르시나요(PROD.로코베리) - 조째즈
6위 | THUNDER - 세븐틴 (SEVENTEEN)
7위 | TOO BAD (feat. Anderson .Paak) - G-DRAGON
8위 | 네모의 꿈 - 아이유
9위 | Whiplash - aespa
10위 | HOME SWEET HOME (feat. 태양, 대성) - G-DRAGON
11위 | 나는 반딧불 - 황가람
12위 | 어제보다 슬픈 오늘 - 우디 (Woody)
13위 | 오늘만 I LOVE YOU - BOYNEXTDOOR
14위 | REBEL HEART - IVE (아이브)
15위 | HAPPY - DAY6 (데이식스)
16위 | 빨간 운동화 - 아이유
17위 | Flower - 오반(OVAN)
18위 | APT. - 로제 (ROSÉ), Bruno Mars
19위 | 청춘만화 - 이무진
20위 | HOT - LE SSERAFIM (르세라핌)
21위 | 10월 4일 - 아이유
22위 | 한 페이지가 될 수 있게 - DAY6 (데이식스)
23위 | Last Scene (Feat. 원슈타인) - 아이유
24위 | HBD - 세븐틴 (SEVENTEEN)
25위 | MY LOVE(2025) - 이예은, 아샤트리, 전건호
26위 | 그날이 오면 - 투모로우바이투게더
27위 | 내게 사랑이 뭐냐고 물어본다면 - 로이킴
28위 | Fly Up - RIIZE
29위 | Welcome to the Show - DAY6 (데이식스)
30위 | 소나기 - 이클립스 (ECLIPSE)
31위 | 천상연 - 이창섭
32위 | Die With A Smile - Lady Gaga, Bruno Mars
33위 | toxic till the end - 로제 (ROSÉ)
34위 | HANDS UP - MEOVV (미야오)
35위 | Supernova - aespa
36위 | 예뻤어 - DAY6 (데이식스)
37위 | Skyfall (THE 8 Solo) - 세븐틴 (SEVENTEEN)
38위 | ATTITUDE - IVE (아이브)
39위 | I DO ME - KiiiKiii (키키)
40위 | 미치게 그리워서 - 황가람
41위 | 미인 (Feat. Balming Tiger) - 아이유
42위 | 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 - AKMU (악뮤)
43위 | DRIP - BABYMONSTER
44위 | Love wins all - 아이유
45위 | PO￦ER - G-DRAGON
46위 | 청혼하지 않을 이유를 못 찾았어 - 이무진
47위 | 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) - 너드커넥션 (Nerd Connection)
48위 | 사랑은 늘 도망가 - 임영웅
49위 | Bad Influence (Prod. by Pharrell Williams) - 세븐틴 (SEVENTEEN)
50위 | 내 이름 맑음 - QWER
51위 | 99.9% (WONWOO Solo) - 세븐틴 (SEVENTEEN)
52위 | 슬픈 초대장 - 순순희(지환)
53위 | 첫 만남은 계획대로 되지 않아 - TWS (투어스)
54위 | Fortunate Change (JOSHUA Solo) - 세븐틴 (SEVENTEEN)
55위 | Raindrops (SEUNGKWAN Solo) - 세븐틴 (SEVENTEEN)
56위 | UP (KARINA Solo) - aespa
57위 | 고민중독 - QWER
58위 | 나는 아픈 건 딱 질색이니까 - i-dle (아이들)
59위 | 주저하는 연인들을 위해 - 잔나비
60위 | TAKE ME - G-DRAGON
61위 | 너의 모든 순간 - 성시경
62위 | 운명 (WOOZI Solo) - 세븐틴 (SEVENTEEN)
63위 | Damage (HOSHI Solo) (feat. Timbaland) - 세븐틴 (SEVENTEEN)
64위 | Happy Virus (DK Solo) - 세븐틴 (SEVENTEEN)
65위 | Magnetic - 아일릿(ILLIT)
66위 | How Sweet - NewJeans
67위 | 사랑인가 봐 - 멜로망스
68위 | I Feel Good - BOYNEXTDOOR
69위 | 에피소드 - 이무진
70위 | 비의 랩소디 - 임재현
71위 | Shake It Off (MINGYU Solo) - 세븐틴 (SEVENTEEN)
72위 | 우연 (JEONGHAN Solo) - 세븐틴 (SEVENTEEN)
73위 | Bag Bad Back - RIIZE
74위 | 123-78 - BOYNEXTDOOR
75위 | 모든 날, 모든 순간 (Every day, Every Moment) - 폴킴
76위 | The Chase - Hearts2Hearts (하츠투하츠)
77위 | 시작의 아이 - 마크툽 (MAKTUB)
78위 | Supersonic - 프로미스나인
79위 | Jungle (S.COUPS Solo) - 세븐틴 (SEVENTEEN)
80위 | 쌍둥이자리 (Gemini) (JUN Solo) - 세븐틴 (SEVENTEEN)
81위 | I AM - IVE (아이브)
82위 | Shining Star (Vernon Solo) - 세븐틴 (SEVENTEEN)
83위 | Hype Boy - NewJeans
84위 | 다정히 내 이름을 부르면 - 경서예지, 전건호
85위 | Seven (feat. Latto) - Clean Ver. - 정국
86위 | 헤어지자 말해요 - 박재정
87위 | Trigger (DINO Solo) - 세븐틴 (SEVENTEEN)
88위 | 영원해 - 도경수(D.O.)
89위 | 이렇게 좋아해 본 적이 없어요 - BOYNEXTDOOR
90위 | 우리들의 블루스 - 임영웅
91위 | 봄날 - 방탄소년단
92위 | 무제(無題) (Untitled, 2014) - G-DRAGON
93위 | 천국보다 아름다운 - 임영웅
94위 | 인사 - 범진
95위 | 굿데이 2025 (텔레파시 + 달빛 창가에서) - G-DRAGON, 황정민, 데프콘, 홍진경, 정형돈, 조세호, 기안84, 안성재, 태양, 정해인, 황광희, 임시완, 이수혁, 대성, 코드 쿤스트 (CODE KUNST), CL, 김고은, DAY6 (데이식스), 부석순 (SEVENTEEN), aespa
96위 | Sticky - KISS OF LIFE
97위 | Small girl (feat. 도경수(D.O.)) - 이영지
98위 | Dash - PLAVE
99위 | 사막에서 꽃을 피우듯 - 우디 (Woody)
100위 | 다시 만날 수 있을까 - 임영웅