In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font color = "red" size = "5">ch14. 웹데이터 수집</font></b>
# 1절. BeautifulSoup
- pip install bs4
- 아나콘다를 설치하면 7500여개의 패키지 자동 설치됨
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests # HTTP 요청 처리 lib
from requests_file import FileAdapter

In [3]:
s = requests.Session() # HTTP 요청 관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get('file:///ai_x/source/01_python/data/ch14_sample.html')
response

In [4]:
response.status_code
# 200 : 정상
# 404 : 없는 페이지
# 406 : get, post 오류
# 500 : python 문법 error

200

In [5]:
# 바이너리 형식의 내용
response.content

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [6]:
response.content.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [7]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [8]:
# html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, # response.text = response.content
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

#### 첫번째함수 soup.select_one('선택자') : 해당 선택자 처음 하나만 가져옴
- select_one(선택자)와 find(태그, 속성)

In [9]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만 가져옴
el = soup.select_one('h1')
print('el : ', el)
print('el.text : ', el.text)
print('el.string : ', el.string)
print('el의 속성들 : ', el.attrs)
print('el의 title속성', el.attrs['title'])
print('el의 title속성', el.attrs.get('title'))
print('el의 이름 : ', el.name)

el :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
el.text :  Hello, CSS
el.string :  Hello, CSS
el의 속성들 :  {'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}
el의 title속성 greeting
el의 title속성 greeting
el의 이름 :  h1

#### 두번째함수 soup.select('선택자') : 해당 선택자 모든 엘리먼트를 리스트로 가져옴

In [10]:
# soup.select('선택자') : 해당 선택자 모든 엘리먼트를 리스트로 가져옴
el = soup.select('h1')
print('리스트 el : ', el)
print('el의 text들 : ', [e.text for e in el])
#for e in el:
#    print(e.text, end=',')
print('el의 속성들 : ', [e.attrs for e in el])
print('el의 class속성들 : ', [e.attrs.get('class') for e in el])

리스트 el :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el의 text들 :  ['Hello, CSS', 'Hi, CSS']
el의 속성들 :  [{'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}, {'class': ['css']}]
el의 class속성들 :  [['greeting', 'css'], ['css']]

#### 세번째함수 find(태그, 속성)

In [11]:
# select_one(선택자)와 find(태그, 속성)
print('select_one : ', soup.select_one('h1.css'))
print('find : ', soup.find('h1', {'class':'css'}))
print('find : ', soup.find('h1', class_='css'))
print('select_one : ', soup.select_one('h1#text'))
print('find : ', soup.find('h1',{'id':'text'}))
print()
print('select')

select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select

#### 네번쨰함수 find_all(태그,속성)

In [12]:
# select(선택자)와 find_all(태그, 속성)
print('모든 h1.css, span 태그(select) : ', soup.select('h1.css, span'))
print('모든 h1.css, span태그(find_all) : ', soup.find_all(['h1','span'], class_='css'))
print() # 개행

모든 h1.css, span 태그(select) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css, span태그(find_all) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

#### 없는 엘리먼트 찾기

In [13]:
# 없는 엘리먼트 찾기
print('find_all(빈리스트) : ', soup.find_all('a', class_='css'))
print('find(None) : ', soup.find('a', class_='css'))
print('select(빈리스트) : ', soup.select('a.css'))
print('select_one(None) : ', soup.select_one('a.css'))

find_all(빈리스트) :  []
find(None) :  None
select(빈리스트) :  []
select_one(None) :  None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
#### json, xml, html
## 2.1 JSON파일
#### requests모듈(get)
#### urllib.request모듈(urlopen)
#### 크롤링 허용 범위는 사이트마다 ~.com/robots.txt에서 확인할 수 있습니다

In [14]:
# 크롤링 허용 범위는 사이트마다 ~.com/robots.txt에서 확인할 수 있습니다

#### 방법1 import requests

In [15]:
# 방법1 
import requests
response = requests.get('https://api.github.com')
response, response.status_code

(<Response [200]>, 200)

#### 방법2 urillib.request모듈(urlopen)

In [16]:
# 방법2
from urllib.request import urlopen
response = urlopen('https://api.github.com')
response

In [17]:
text = '{"속성1":"값1", "속성2":"값2"}'
type(text)

str

In [18]:
# 문자(딕셔너리 타입)를 딕셔너리
#'{"속성1":"값1", "속성2":"값2"}' => {"속성1":"값1", "속성2":"값2"}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2'}

## 2.2 html 파일
### 1) 환율정보 가져오기(네이버->증권->시장지표)
- https://finance.naver.com/marketindex/

#### 방법1 requests모듈

In [19]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
#response, response.status_code
#response.content
#response.content.decode('cp949')
#response.text
soup = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

#### 방법2 from urllib.request import urlopen

In [20]:
# 방법2 from urllib.request import urlopen
from urllib.request import urlopen
response = urlopen(url)
#response.status
#response.read().decode('cp949')
soup = BeautifulSoup(response, # response.read()
                     'html.parser')

In [21]:
title = soup.select('h3.h_lst > span.blind')
for t in title:
    print(t.text, end='\t')

미국 USD	일본 JPY(100엔)	유럽연합 EUR	중국 CNY	달러/일본 엔	유로/달러	영국 파운드/달러	달러인덱스	WTI	휘발유	국제 금	국내 금

In [22]:
price = soup.select('div.head_info > span.value')
[p.text for p in price]
[round(float(p.text.replace(',',''))) for p in price]
[round(float(''.join(p.text.split(',')))) for p in price]

[1372, 952, 1553, 191, 144, 1, 1, 99, 61, 1633, 3300, 146093]

In [23]:
out = '1,375.20'
round(float(''.join(out.split(','))))

1375

In [24]:
round(float(out.replace(',','')))

1375

In [25]:
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7, '') # 7번째 index에 '' 추가
unit

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [26]:
status = soup.select('div.head_info > span.blind')
[t.text for t in title]
[p.text for p in price]
unit
[s.string for s in status]

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '상승']

In [27]:
len(title), len(price), len(unit), len(status)

(12, 12, 12, 12)

In [28]:
for idx in range(len(title)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                  title[idx].text,
                                 price[idx].text,
                                 unit[idx],
                                 status[idx].text))

1. 미국 USD : 1,372.10원 - 하락
2. 일본 JPY(100엔) : 952.02원 - 하락
3. 유럽연합 EUR : 1,553.01원 - 하락
4. 중국 CNY : 190.89원 - 하락
5. 달러/일본 엔 : 144.3800엔 - 상승
6. 유로/달러 : 1.1342달러 - 하락
7. 영국 파운드/달러 : 1.3520달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.96원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 146093.27원 - 상승

In [29]:
for t, p, u, s in zip(title, price, unit, status):
    print("{} : {}{} - {}".format(t.text,
                                 p.text,
                                 u,
                                 s.text))

미국 USD : 1,372.10원 - 하락
일본 JPY(100엔) : 952.02원 - 하락
유럽연합 EUR : 1,553.01원 - 하락
중국 CNY : 190.89원 - 하락
달러/일본 엔 : 144.3800엔 - 상승
유로/달러 : 1.1342달러 - 하락
영국 파운드/달러 : 1.3520달러 - 하락
달러인덱스 : 99.4200 - 상승
WTI : 60.89달러 - 하락
휘발유 : 1632.96원 - 하락
국제 금 : 3300.4달러 - 하락
국내 금 : 146093.27원 - 상승

In [30]:
for idx, (t, p, u, s) in enumerate(zip(title, price, unit, status)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                      t.text,
                                 p.text,
                                 u,
                                 s.text))

1. 미국 USD : 1,372.10원 - 하락
2. 일본 JPY(100엔) : 952.02원 - 하락
3. 유럽연합 EUR : 1,553.01원 - 하락
4. 중국 CNY : 190.89원 - 하락
5. 달러/일본 엔 : 144.3800엔 - 상승
6. 유로/달러 : 1.1342달러 - 하락
7. 영국 파운드/달러 : 1.3520달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.96원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 146093.27원 - 상승

### 2) 이번주 로또번호 출력
- google에 "로또번호 당첨번호" 검색
https://dhlottery.co.kr/gameResult.do?method=byWin
```
1173회 당첨결과
(2025년 05월 24일 추첨)
당첨번호 [1,5,18,20,30,35]
보너스 3
```

In [31]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

In [32]:
# 방법2 urlopen
from urllib.request import urlopen
response = urlopen(url)
soup = BeautifulSoup(response, "html.parser")

In [33]:
times = soup.select_one('div.win_result > h4 > strong').text
date = soup.select_one('div.win_result > p.desc').text
title1 = soup.select_one('div.num.win>strong').text
lotto_number = soup.select('div.num.win>p>span')
title2 = soup.select_one('div.num.bonus>strong').string
bonus_number = soup.select_one('div.num.bonus > p > span').text
print( times, date, title1, [int(lotto.text) for lotto in lotto_number]
     , title2, bonus_number)

# for t in times:
#     print(t.text, end='\t')

1173회 (2025년 05월 24일 추첨) 당첨번호 [1, 5, 18, 20, 30, 35] 보너스 3

In [34]:
# 위의 select 함수를 find함수로
# times = soup.select_one('div.win_result > h4 > strong').text
win_result = soup.find('div', class_="win_result")
times = win_result.find('strong').text

# date = soup.select_one('div.win_result > p.desc').text
date = soup.find('p', class_='desc').text

print(times, date)

# title1 = soup.select_one('div.num.win>strong').text
num_win = soup.find('div', class_=['win'])
title1 = num_win.find('strong').text

# lotto_number = soup.select('div.num.win>p>span')
lotto_number = num_win.find_all('span') # 배열

print(title1, [int(lotto.text) for lotto in lotto_number])

# title2 = soup.select_one('div.num.bonus>strong').string
num_bonus = soup.find('div', class_=['bonus'])
title2 = num_bonus.find('strong').text

print(num_bonus)

# bonus_number = soup.select_one('div.num.bonus > p > span').text
bonus_number = num_bonus.find('span').text

print( times, date, title1, [int(lotto.text) for lotto in lotto_number]
     , title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
<div class="num bonus">
<strong>보너스</strong>
<p><span class="ball_645 lrg ball1">3</span></p>
</div>
1173회 (2025년 05월 24일 추첨) 당첨번호 [1, 5, 18, 20, 30, 35] 보너스 3

### 3) 다음 검색 리스트
```
no             title                     link
0   [비트코인 2025] 백악관 크립토 차르~      https://v.daum.net/v/20250528103907230
1   [비즈 나우] 비트코인 2025 컨퍼런스 개막~  https://v.daum.net/v/20250528075215864
...
```

#### 방법1

In [35]:
# 방법1
import requests
from bs4 import BeautifulSoup

word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
print(url)
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no':idx,
                           'title':item.text,
                           'link':item.attrs['href']})
import pandas as pd
pd.DataFrame(items_find_list)

https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8비트코인

,no,title,link
0,0,EU관세 발언 후 10만8000달러선 회복 비트코인…파키스탄 ‘비트코인 채굴’ 전...,http://v.daum.net/v/20250526080440640
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
3,3,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
4,4,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
5,5,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
6,6,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
7,7,"10만 달러, 11만 달러… 트럼프 관세 변덕에 비트코인 '출렁'",http://v.daum.net/v/20250527132843430
8,8,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
9,9,'해킹 산업화'의 원흉 '비트코인'…위치추적 안 되자 활개[은폐⑥],http://v.daum.net/v/20250527090029503

In [36]:
import requests
from bs4 import BeautifulSoup

word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
print(url)
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 2차원 리스트

items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')

for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
items_find_list
import pandas as pd
pd.DataFrame(items_find_list, columns=['no', 'title', 'link'])

https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8비트코인

,no,title,link
0,0,EU관세 발언 후 10만8000달러선 회복 비트코인…파키스탄 ‘비트코인 채굴’ 전...,http://v.daum.net/v/20250526080440640
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
3,3,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
4,4,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
5,5,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
6,6,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
7,7,"10만 달러, 11만 달러… 트럼프 관세 변덕에 비트코인 '출렁'",http://v.daum.net/v/20250527132843430
8,8,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
9,9,'해킹 산업화'의 원흉 '비트코인'…위치추적 안 되자 활개[은폐⑥],http://v.daum.net/v/20250527090029503

#### 다음 뉴스 검색(키워드, 원하는 페이지수)

In [37]:
# 다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

keyword = '비트코인'
page = 2
# url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={page}'
url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
params = {'q':keyword,
          'p':page}

response = requests.get(url, params=params)

#
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
#     print({'no': (page-1)*10 + idx,
#                            'title':item.text,
#                            'link':item.attrs['href']})

In [38]:
# 함수만들기
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword,
          'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
    items_find_list = [] # 검색결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
    return items_find_list

In [39]:
collect_list('비트코인', 2)

[{'no': 10,
  'title': ' [대선공약] 가상자산 현물 ETF·토큰증권 확산 공감대…코인 육성 빨라진다 ',
  'link': 'http://v.daum.net/v/20250528174700772'},
 {'no': 11,
  'title': " 숨 고르는 비트코인, 10만8000달러선 '주춤' ",
  'link': 'http://v.daum.net/v/20250528095921258'},
 {'no': 12,
  'title': ' “맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터] ',
  'link': 'http://v.daum.net/v/20250528143002735'},
 {'no': 13,
  'title': ' 연일 최고가 경신하는 비트코인…투자자들 강 건너 불구경하는 이유는 ',
  'link': 'http://v.daum.net/v/20250526212400275'},
 {'no': 14,
  'title': ' "비트코인 산다"…트럼프家, 25억달러 자금 조달 추진[코인브리핑] ',
  'link': 'http://v.daum.net/v/20250528111837527'},
 {'no': 15,
  'title': ' [김대호 박사의 오늘의 키워드] 소비자신뢰지수·비트코인 2025·머스크 한마디·애플 괘씸죄 ',
  'link': 'http://v.daum.net/v/20250528071325361'},
 {'no': 16,
  'title': ' [포토]라스베이거스에서 열린 2025 비트코인 콘퍼런스 ',
  'link': 'http://v.daum.net/v/20250528155536962'},
 {'no': 17,
  'title': ' 비트코인과 엇갈리는 이더리움·리플, 왜? ',
  'link': 'http://v.daum.net/v/20250526164319028'},
 {'no': 18,
  'title': " 대주주 먹튀 근절·상법개정…'코스피 5000' 뒷받침 공약 발표 ",
  'link': 'http://v.daum.net/v/20250528164529582'},
 {'no': 19,
  'title': ' <단독>"예배 참석하면 코인 드려요. 5년 안에 비트코인 넘어섭니다"..신앙심 노린 코인 유사 사기 기승 ',
  'link': 'http://v.daum.net/v/20250528083323774'}]

#### 원하는 keyword로 다음검색

In [40]:
# 원하는 keyword로 다음검색
result = []
keyword = "청바지"
pages = 4
for page in range(1, pages+1):
    result.extend(collect_list(keyword, page))
    time.sleep(3)
result_df = pd.DataFrame(result)
result_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [41]:
keywords = ['청바지','면바지']
pages = 2

result0 = [] # 청바지 검색결과 20개
result1 = [] # 면바지 검색결과 20개

for i, keyword in enumerate(keywords):
    print(f'...loading... {i}번째 {keyword} 검색중입니다.')
    for page in range(1, pages+1):
#         print(f'...loading... {i}번째 {keyword} {page} 검색중입니다.')
        if i == 0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(1)

...loading... 0번째 청바지 검색중입니다.
...loading... 1번째 면바지 검색중입니다.

In [42]:
result0_df = pd.DataFrame(result0)
result0_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [43]:
result1_df = pd.DataFrame(result1)
result1_df.head()

,no,title,link
0,0,사천에서 쾌청한 날씨 속 탁 트인 남해 풍경 즐겨요!,http://v.daum.net/v/20250528104429529
1,1,"윤승아, ♥김무열 쏙 빼닮은 깜찍 子 하객룩 공개‥벌써 우월한 유전자",http://v.daum.net/v/20250526145941690
2,2,"이번 주 포천 여행,반팔 하나로 충분할까?",http://v.daum.net/v/20250527171732518
3,3,"이재명, 첫 대학 방문…이준석 겨냥?",http://v.daum.net/v/20250526191942751
4,4,"""나는 젊어"" 팔소매 접은 이준석의 '흰셔츠' 속에도 뼈가 담겼다[21대 대선 리...",http://v.daum.net/v/20250525070013619

In [44]:
collect_list("청바지", 1)

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

In [45]:
result0_df.to_csv('data/ch14_'+keyword[0]+'.csv', index=False, encoding='cp949')
result1_df.to_csv('data/ch14_'+keyword[1]+'.csv', index=False, encoding='utf-8')

### 4) User-Agent를 추가하여 크롤링
- urlopen()함수를 사용하면 크롤링이 안되는 사이트
- User-Agent를 추가하여 크롤링

In [46]:
# 방법2 : urlopen()함수를 사용하면 크롤링이 안되는 사이트
# robots.txt에 Disallow로 되어 있는 경우
from urllib.request import urlopen, Request
import urllib.parse
word = '비트코인'
word = urllib.parse.quote(word)
print(word)
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=\
%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'+word
# User-Agent를 추가하여 브라우저처럼 보이게 포장
headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
response = urlopen(request)
soup = BeautifulSoup(response, # response.content
                    "html.parser")

def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword,
          'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
    items_find_list = [] # 검색결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                           'title':item.text,
                           'link':item.attrs['href']})
    return items_find_list

collect_list("청바지", 1)

%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

### 꼭 User-Agent를 사용하여야 하는 경우 : https://www.melon.com/chart/

In [47]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'

melonpage = requests.get(url)
melonpage

In [48]:
# 방법2
from urllib.request import urlopen, Request
# 에러남
# melonpage = urlopen(url)
# melonpage

#### 멜론 100차트 연습

In [49]:
# User-Agent 추가
headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
# 방법2
request = Request(url, headers=headers)
melonpage = urlopen(request)

# 방법1
melonpage = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, # melonpage.content
                    "html.parser")
# soup

In [51]:
# 멜론 순위, 노래 제목, 가수, 좋아요
rank1 = [r.text for r in soup.select('div.wrap.t_center > span.rank')][1:]
title1 = [t.text for t in soup.select('div.wrap_song_info > div.ellipsis.rank01 > span > a')]
singer1 = [s.text for s in soup.select('div.wrap_song_info > div.ellipsis.rank02 > a')]
print(rank1, title1, singer1)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100'] ['너에게 닿기를', 'Never Ending Story', 'Drowning', 'like JENNIE', '모르시나요(PROD.로코베리)', 'THUNDER', 'TOO BAD (feat. Anderson .Paak)', '네모의 꿈', 'Whiplash', 'HOME SWEET HOME (feat. 태양, 대성)', '나는 반딧불', '어제보다 슬픈 오늘', '오늘만 I LOVE YOU', 'REBEL HEART', 'HAPPY', '빨간 운동화', 'Flower', 'APT.', '청춘만화', 'HOT', '10월 4일', '한 페이지가 될 수 있게', 'Last Scene (Feat. 원슈타인)', 'HBD', 'MY LOVE(2025)', '그날이 오면', '내게 사랑이 뭐냐고 물어본다면', 'Fly Up', 'Welcome to the Show', '소나기', '천상연', 'Die With A Smile', 'toxic till the end', 'HANDS UP', 'Supernova', '예뻤어', 'Skyfall (THE 8 Solo)', 'ATTITUDE', 'I DO ME', '미치게 그리워서', '미인 (Feat. Balming Tiger)', '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'DRIP', 'Love wins all', 'PO￦ER', '청혼하지 않을 이유를 못 찾았어', '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))', '사랑은 늘 도망가', 'Bad Influence (Prod. by Pharrell Williams)', '내 이름 맑음', '99.9% (WONWOO Solo)', '슬픈 초대장', '첫 만남은 계획대로 되지 않아', 'Fortunate Change (JOSHUA Solo)', 'Raindrops (SEUNGKWAN Solo)', 'UP (KARINA Solo)', '고민중독', '나는 아픈 건 딱 질색이니까', '주저하는 연인들을 위해', 'TAKE ME', '너의 모든 순간', '운명 (WOOZI Solo)', 'Damage (HOSHI Solo) (feat. Timbaland)', 'Happy Virus (DK Solo)', 'Magnetic', 'How Sweet', '사랑인가 봐', 'I Feel Good', '에피소드', '비의 랩소디', 'Shake It Off (MINGYU Solo)', '우연 (JEONGHAN Solo)', 'Bag Bad Back', '123-78', '모든 날, 모든 순간 (Every day, Every Moment)', 'The Chase', '시작의 아이', 'Supersonic', 'Jungle (S.COUPS Solo)', '쌍둥이자리 (Gemini) (JUN Solo)', 'I AM', 'Shining Star (Vernon Solo)', 'Hype Boy', '다정히 내 이름을 부르면', 'Seven (feat. Latto) - Clean Ver.', '헤어지자 말해요', 'Trigger (DINO Solo)', '영원해', '이렇게 좋아해 본 적이 없어요', '우리들의 블루스', '봄날', '무제(無題) (Untitled, 2014)', '천국보다 아름다운', '인사', '굿데이 2025 (텔레파시 + 달빛 창가에서)', 'Sticky', 'Small girl (feat. 도경수(D.O.))', 'Dash', '사막에서 꽃을 피우듯', '다시 만날 수 있을까'] ['10CM', '아이유', 'WOODZ', '제니 (JENNIE)', '조째즈', '세븐틴 (SEVENTEEN)', 'G-DRAGON', '아이유', 'aespa', 'G-DRAGON', '황가람', '우디 (Woody)', 'BOYNEXTDOOR', 'IVE (아이브)', 'DAY6 (데이식스)', '아이유', '오반(OVAN)', '로제 (ROSÉ)', 'Bruno Mars', '이무진', 'LE SSERAFIM (르세라핌)', '아이유', 'DAY6 (데이식스)', '아이유', '세븐틴 (SEVENTEEN)', '이예은', '아샤트리', '전건호', '투모로우바이투게더', '로이킴', 'RIIZE', 'DAY6 (데이식스)', '이클립스 (ECLIPSE)', '이창섭', 'Lady Gaga', 'Bruno Mars', '로제 (ROSÉ)', 'MEOVV (미야오)', 'aespa', 'DAY6 (데이식스)', '세븐틴 (SEVENTEEN)', 'IVE (아이브)', 'KiiiKiii (키키)', '황가람', '아이유', 'AKMU (악뮤)', 'BABYMONSTER', '아이유', 'G-DRAGON', '이무진', '너드커넥션 (Nerd Connection)', '임영웅', '세븐틴 (SEVENTEEN)', 'QWER', '세븐틴 (SEVENTEEN)', '순순희(지환)', 'TWS (투어스)', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'aespa', 'QWER', 'i-dle (아이들)', '잔나비', 'G-DRAGON', '성시경', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', '아일릿(ILLIT)', 'NewJeans', '멜로망스', 'BOYNEXTDOOR', '이무진', '임재현', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'RIIZE', 'BOYNEXTDOOR', '폴킴', 'Hearts2Hearts (하츠투하츠)', '마크툽 (MAKTUB)', '프로미스나인', '세븐틴 (SEVENTEEN)', '세븐틴 (SEVENTEEN)', 'IVE (아이브)', '세븐틴 (SEVENTEEN)', 'NewJeans', '경서예지', '전건호', '정국', '박재정', '세븐틴 (SEVENTEEN)', '도경수(D.O.)', 'BOYNEXTDOOR', '임영웅', '방탄소년단', 'G-DRAGON', '임영웅', '범진', 'G-DRAGON', '황정민', '데프콘', '홍진경', '정형돈', '조세호', '기안84', '안성재', '태양', '정해인', '황광희', '임시완', '이수혁', '대성', '코드 쿤스트 (CODE KUNST)', 'CL', '김고은', 'DAY6 (데이식스)', '부석순 (SEVENTEEN)', 'aespa', 'KISS OF LIFE', '이영지', 'PLAVE', '우디 (Woody)', '임영웅']

In [53]:
result = []
for idx in range(len(title1)):
    rank = rank1[idx]
    title2 = title1[idx]
    singer = singer1[idx]
    print(f"{rank} : {title2} - {singer}")    
    result.append([idx + 1, rank, title2, singer])

1 : 너에게 닿기를 - 10CM
2 : Never Ending Story - 아이유
3 : Drowning - WOODZ
4 : like JENNIE - 제니 (JENNIE)
5 : 모르시나요(PROD.로코베리) - 조째즈
6 : THUNDER - 세븐틴 (SEVENTEEN)
7 : TOO BAD (feat. Anderson .Paak) - G-DRAGON
8 : 네모의 꿈 - 아이유
9 : Whiplash - aespa
10 : HOME SWEET HOME (feat. 태양, 대성) - G-DRAGON
11 : 나는 반딧불 - 황가람
12 : 어제보다 슬픈 오늘 - 우디 (Woody)
13 : 오늘만 I LOVE YOU - BOYNEXTDOOR
14 : REBEL HEART - IVE (아이브)
15 : HAPPY - DAY6 (데이식스)
16 : 빨간 운동화 - 아이유
17 : Flower - 오반(OVAN)
18 : APT. - 로제 (ROSÉ)
19 : 청춘만화 - Bruno Mars
20 : HOT - 이무진
21 : 10월 4일 - LE SSERAFIM (르세라핌)
22 : 한 페이지가 될 수 있게 - 아이유
23 : Last Scene (Feat. 원슈타인) - DAY6 (데이식스)
24 : HBD - 아이유
25 : MY LOVE(2025) - 세븐틴 (SEVENTEEN)
26 : 그날이 오면 - 이예은
27 : 내게 사랑이 뭐냐고 물어본다면 - 아샤트리
28 : Fly Up - 전건호
29 : Welcome to the Show - 투모로우바이투게더
30 : 소나기 - 로이킴
31 : 천상연 - RIIZE
32 : Die With A Smile - DAY6 (데이식스)
33 : toxic till the end - 이클립스 (ECLIPSE)
34 : HANDS UP - 이창섭
35 : Supernova - Lady Gaga
36 : 예뻤어 - Bruno Mars
37 : Skyfall (THE 8 Solo) - 로제 (ROSÉ)
38 : ATTITUDE - MEOVV (미야오)
39 : I DO ME - aespa
40 : 미치게 그리워서 - DAY6 (데이식스)
41 : 미인 (Feat. Balming Tiger) - 세븐틴 (SEVENTEEN)
42 : 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 - IVE (아이브)
43 : DRIP - KiiiKiii (키키)
44 : Love wins all - 황가람
45 : PO￦ER - 아이유
46 : 청혼하지 않을 이유를 못 찾았어 - AKMU (악뮤)
47 : 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) - BABYMONSTER
48 : 사랑은 늘 도망가 - 아이유
49 : Bad Influence (Prod. by Pharrell Williams) - G-DRAGON
50 : 내 이름 맑음 - 이무진
51 : 99.9% (WONWOO Solo) - 너드커넥션 (Nerd Connection)
52 : 슬픈 초대장 - 임영웅
53 : 첫 만남은 계획대로 되지 않아 - 세븐틴 (SEVENTEEN)
54 : Fortunate Change (JOSHUA Solo) - QWER
55 : Raindrops (SEUNGKWAN Solo) - 세븐틴 (SEVENTEEN)
56 : UP (KARINA Solo) - 순순희(지환)
57 : 고민중독 - TWS (투어스)
58 : 나는 아픈 건 딱 질색이니까 - 세븐틴 (SEVENTEEN)
59 : 주저하는 연인들을 위해 - 세븐틴 (SEVENTEEN)
60 : TAKE ME - aespa
61 : 너의 모든 순간 - QWER
62 : 운명 (WOOZI Solo) - i-dle (아이들)
63 : Damage (HOSHI Solo) (feat. Timbaland) - 잔나비
64 : Happy Virus (DK Solo) - G-DRAGON
65 : Magnetic - 성시경
66 : How Sweet - 세븐틴 (SEVENTEEN)
67 : 사랑인가 봐 - 세븐틴 (SEVENTEEN)
68 : I Feel Good - 세븐틴 (SEVENTEEN)
69 : 에피소드 - 아일릿(ILLIT)
70 : 비의 랩소디 - NewJeans
71 : Shake It Off (MINGYU Solo) - 멜로망스
72 : 우연 (JEONGHAN Solo) - BOYNEXTDOOR
73 : Bag Bad Back - 이무진
74 : 123-78 - 임재현
75 : 모든 날, 모든 순간 (Every day, Every Moment) - 세븐틴 (SEVENTEEN)
76 : The Chase - 세븐틴 (SEVENTEEN)
77 : 시작의 아이 - RIIZE
78 : Supersonic - BOYNEXTDOOR
79 : Jungle (S.COUPS Solo) - 폴킴
80 : 쌍둥이자리 (Gemini) (JUN Solo) - Hearts2Hearts (하츠투하츠)
81 : I AM - 마크툽 (MAKTUB)
82 : Shining Star (Vernon Solo) - 프로미스나인
83 : Hype Boy - 세븐틴 (SEVENTEEN)
84 : 다정히 내 이름을 부르면 - 세븐틴 (SEVENTEEN)
85 : Seven (feat. Latto) - Clean Ver. - IVE (아이브)
86 : 헤어지자 말해요 - 세븐틴 (SEVENTEEN)
87 : Trigger (DINO Solo) - NewJeans
88 : 영원해 - 경서예지
89 : 이렇게 좋아해 본 적이 없어요 - 전건호
90 : 우리들의 블루스 - 정국
91 : 봄날 - 박재정
92 : 무제(無題) (Untitled, 2014) - 세븐틴 (SEVENTEEN)
93 : 천국보다 아름다운 - 도경수(D.O.)
94 : 인사 - BOYNEXTDOOR
95 : 굿데이 2025 (텔레파시 + 달빛 창가에서) - 임영웅
96 : Sticky - 방탄소년단
97 : Small girl (feat. 도경수(D.O.)) - G-DRAGON
98 : Dash - 임영웅
99 : 사막에서 꽃을 피우듯 - 범진
100 : 다시 만날 수 있을까 - G-DRAGON

In [64]:
import pandas as pd
parsed_result = [[item[2], item[3]] for item in result]

df = pd.DataFrame(parsed_result, columns=['title', 'singer'], index=range(1, len(parsed_result) + 1))
df

                            title       singer
1                         너에게 닿기를         10CM
2              Never Ending Story          아이유
3                        Drowning        WOODZ
4                     like JENNIE  제니 (JENNIE)
5                모르시나요(PROD.로코베리)          조째즈
..                            ...          ...
96                         Sticky        방탄소년단
97   Small girl (feat. 도경수(D.O.))     G-DRAGON
98                           Dash          임영웅
99                    사막에서 꽃을 피우듯           범진
100                   다시 만날 수 있을까     G-DRAGON

[100 rows x 2 columns]

#### 멜론 100차트 연습 선생님ver

In [61]:
title_els = soup.select('div.ellipsis.rank01 > span')
singer_els = soup.select('div.ellipsis.rank02 > span.checkEllipsis')
len([title.text.strip() for title in title_els]), \
len([singer.text for singer in singer_els])
for idx, (title, singer) in enumerate(zip(title_els, singer_els)):
    print('{}위 | {} - {}'.format(idx+1,
                                 title.text.strip(),
                                 singer.text))

1위 | 너에게 닿기를 - 10CM
2위 | Never Ending Story - 아이유
3위 | Drowning - WOODZ
4위 | like JENNIE - 제니 (JENNIE)
5위 | 모르시나요(PROD.로코베리) - 조째즈
6위 | THUNDER - 세븐틴 (SEVENTEEN)
7위 | TOO BAD (feat. Anderson .Paak) - G-DRAGON
8위 | 네모의 꿈 - 아이유
9위 | Whiplash - aespa
10위 | HOME SWEET HOME (feat. 태양, 대성) - G-DRAGON
11위 | 나는 반딧불 - 황가람
12위 | 어제보다 슬픈 오늘 - 우디 (Woody)
13위 | 오늘만 I LOVE YOU - BOYNEXTDOOR
14위 | REBEL HEART - IVE (아이브)
15위 | HAPPY - DAY6 (데이식스)
16위 | 빨간 운동화 - 아이유
17위 | Flower - 오반(OVAN)
18위 | APT. - 로제 (ROSÉ), Bruno Mars
19위 | 청춘만화 - 이무진
20위 | HOT - LE SSERAFIM (르세라핌)
21위 | 10월 4일 - 아이유
22위 | 한 페이지가 될 수 있게 - DAY6 (데이식스)
23위 | Last Scene (Feat. 원슈타인) - 아이유
24위 | HBD - 세븐틴 (SEVENTEEN)
25위 | MY LOVE(2025) - 이예은, 아샤트리, 전건호
26위 | 그날이 오면 - 투모로우바이투게더
27위 | 내게 사랑이 뭐냐고 물어본다면 - 로이킴
28위 | Fly Up - RIIZE
29위 | Welcome to the Show - DAY6 (데이식스)
30위 | 소나기 - 이클립스 (ECLIPSE)
31위 | 천상연 - 이창섭
32위 | Die With A Smile - Lady Gaga, Bruno Mars
33위 | toxic till the end - 로제 (ROSÉ)
34위 | HANDS UP - MEOVV (미야오)
35위 | Supernova - aespa
36위 | 예뻤어 - DAY6 (데이식스)
37위 | Skyfall (THE 8 Solo) - 세븐틴 (SEVENTEEN)
38위 | ATTITUDE - IVE (아이브)
39위 | I DO ME - KiiiKiii (키키)
40위 | 미치게 그리워서 - 황가람
41위 | 미인 (Feat. Balming Tiger) - 아이유
42위 | 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 - AKMU (악뮤)
43위 | DRIP - BABYMONSTER
44위 | Love wins all - 아이유
45위 | PO￦ER - G-DRAGON
46위 | 청혼하지 않을 이유를 못 찾았어 - 이무진
47위 | 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) - 너드커넥션 (Nerd Connection)
48위 | 사랑은 늘 도망가 - 임영웅
49위 | Bad Influence (Prod. by Pharrell Williams) - 세븐틴 (SEVENTEEN)
50위 | 내 이름 맑음 - QWER
51위 | 99.9% (WONWOO Solo) - 세븐틴 (SEVENTEEN)
52위 | 슬픈 초대장 - 순순희(지환)
53위 | 첫 만남은 계획대로 되지 않아 - TWS (투어스)
54위 | Fortunate Change (JOSHUA Solo) - 세븐틴 (SEVENTEEN)
55위 | Raindrops (SEUNGKWAN Solo) - 세븐틴 (SEVENTEEN)
56위 | UP (KARINA Solo) - aespa
57위 | 고민중독 - QWER
58위 | 나는 아픈 건 딱 질색이니까 - i-dle (아이들)
59위 | 주저하는 연인들을 위해 - 잔나비
60위 | TAKE ME - G-DRAGON
61위 | 너의 모든 순간 - 성시경
62위 | 운명 (WOOZI Solo) - 세븐틴 (SEVENTEEN)
63위 | Damage (HOSHI Solo) (feat. Timbaland) - 세븐틴 (SEVENTEEN)
64위 | Happy Virus (DK Solo) - 세븐틴 (SEVENTEEN)
65위 | Magnetic - 아일릿(ILLIT)
66위 | How Sweet - NewJeans
67위 | 사랑인가 봐 - 멜로망스
68위 | I Feel Good - BOYNEXTDOOR
69위 | 에피소드 - 이무진
70위 | 비의 랩소디 - 임재현
71위 | Shake It Off (MINGYU Solo) - 세븐틴 (SEVENTEEN)
72위 | 우연 (JEONGHAN Solo) - 세븐틴 (SEVENTEEN)
73위 | Bag Bad Back - RIIZE
74위 | 123-78 - BOYNEXTDOOR
75위 | 모든 날, 모든 순간 (Every day, Every Moment) - 폴킴
76위 | The Chase - Hearts2Hearts (하츠투하츠)
77위 | 시작의 아이 - 마크툽 (MAKTUB)
78위 | Supersonic - 프로미스나인
79위 | Jungle (S.COUPS Solo) - 세븐틴 (SEVENTEEN)
80위 | 쌍둥이자리 (Gemini) (JUN Solo) - 세븐틴 (SEVENTEEN)
81위 | I AM - IVE (아이브)
82위 | Shining Star (Vernon Solo) - 세븐틴 (SEVENTEEN)
83위 | Hype Boy - NewJeans
84위 | 다정히 내 이름을 부르면 - 경서예지, 전건호
85위 | Seven (feat. Latto) - Clean Ver. - 정국
86위 | 헤어지자 말해요 - 박재정
87위 | Trigger (DINO Solo) - 세븐틴 (SEVENTEEN)
88위 | 영원해 - 도경수(D.O.)
89위 | 이렇게 좋아해 본 적이 없어요 - BOYNEXTDOOR
90위 | 우리들의 블루스 - 임영웅
91위 | 봄날 - 방탄소년단
92위 | 무제(無題) (Untitled, 2014) - G-DRAGON
93위 | 천국보다 아름다운 - 임영웅
94위 | 인사 - 범진
95위 | 굿데이 2025 (텔레파시 + 달빛 창가에서) - G-DRAGON, 황정민, 데프콘, 홍진경, 정형돈, 조세호, 기안84, 안성재, 태양, 정해인, 황광희, 임시완, 이수혁, 대성, 코드 쿤스트 (CODE KUNST), CL, 김고은, DAY6 (데이식스), 부석순 (SEVENTEEN), aespa
96위 | Sticky - KISS OF LIFE
97위 | Small girl (feat. 도경수(D.O.)) - 이영지
98위 | Dash - PLAVE
99위 | 사막에서 꽃을 피우듯 - 우디 (Woody)
100위 | 다시 만날 수 있을까 - 임영웅

### 5) 네이버 지식인으로 검색(open API 사용X)
- 특정 keyword를 특정페이지 수(3)만큼 검색한 결과를 데이터프레임으로 출력

#### 방법 1, 2
```
# 방법1
from requests import get

# 방법2
from urllib.request import urlopen
```

In [5]:
# 방법1
from requests import get
from bs4 import BeautifulSoup
keyword = '챗지피티'
url = 'https://kin.naver.com/search/list.naver?query={}'.format(keyword)
# print(url)
response = get(url)
# response.status_code #200(정상) 상태확인
soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
# soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta contents="always" name="referrer"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="챗지피티의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." name="description">
<meta content="width=1024" name="viewport"/>
<meta content="none" name="msapplication-config">
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/components.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/other.css" rel="stylesheet" type="text/css"/>
<script>

	var pcDomain = "kin.naver.com";
	var pcDomainWithProtocol = "https://kin.naver.com";
	var pcKinServiceProtocol = "https";

	var mobileDomain = "m.kin.naver.com";
	var mobileDomainWithProtocol = "https://m.kin.naver.com";
	var mobileKinServiceProtocol = "https";

	var uploadDomain = "upload.kin.naver.com";
	var uploadDomainWithProtocol = "https://upload.kin.naver.com";
	var uploadKinServiceProtocol = "https";
</script>
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/kin.js" type="text/javascript"></script>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="noindex,nofollow" name="robots">
<meta content="챗지피티 검색결과 : 네이버 지식iN" property="og:title">
<meta content="https://kin.naver.com/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0" property="og:url"/>
<meta content="https://ssl.pstatic.net/static/kin/common/kin_thumbnail_new_w1000.png" property="og:image"/>
<meta content="챗지피티의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." property="og:description"/>
<meta content="네이버 지식iN" property="og:article:author"/>
<meta content="https://kin.naver.com" property="og:article:author:url"/>
<link href="/favicon.ico?v=2.4" rel="shortcut icon" type="image/x-icon"/>
<title>
	챗지피티 검색결과 : 지식iN
</title>
<script type="text/javascript">

if ( typeof window.nhn  == "undefined" ) window.nhn = {};
if ( typeof window.naver  == "undefined" ) window.naver = {};
nhn.isLogin = false;
nhn.isJunior = ("N"=="Y");
nhn.isKinUser = false;
nhn.isPortableDevice = false;
nhn.jsDir = 'https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min';

var g_ssc = ("kin.search" == "") ? "kin.temp" : "kin.search";
var ccsrv="cc.naver.com";


var kinRos = {
	bIsNoticeDisplay : ("false" == "" || "false" == "false") ? false : true,
	bIsActionNoticeDisplay : ("false" == "" || "false" == "false") ? false : true

};





var standardReportPopupUrl = "https://srp2.naver.com/report";


var baUserKey = "__UNKNOWN__";
var baLogEndpoint = "https://scv-kin.io.naver.com/jackpotlog/v1/logs";
var baAbTestResult = null;
</script>
</meta></meta></meta></meta></head>
<body>
<div id="loadingIndicator" style="display:none;width:100%;height:100%;position:fixed;top:0px;left:0px;background-color:transparent;z-index:10000;">
<img alt="데이터 요청 응답 대기중" height="21" src="https://ssl.pstatic.net/static/kin/m/ico_lod2.gif" style="position:absolute;top:49%;left:49%;" width="21"/>
</div>
<div class="wrap wrap_search" id="wrap">
<div class="skip_nav header_gnb_inner">
<a class="skip" href="#gnb" onclick="nhn.Kin.Utility.skipNavigation('au_lnb_home');return false;">메인 메뉴 바로가기</a>
<a class="skip" href="#s_content" onclick="nhn.Kin.Utility.skipNavigation('s_content');return false;">본문 바로가기</a>
</div>
<div class="header_wrap">
<div aria-labelledby="ieUpdateBannerTitle" class="popup popup--header_notice" id="ieUpdateBanner" role="dialog" style="display: none;">
<h1 class="blind" id="ieUpdateBannerTitle" tabindex="0">권장 브라우저 업데이트 안내</h1>
<div class="popup__content">
<div class="popup__title">
<p class="popup__title_text"><span class="ico_alert sp_common"></span>권장 브라우저 안내</p>
</div>
<div class="popup__maintext">
<p class="popup__text">혹시 아직 인터넷 익스플로러 9.0 미만 버전을 사용하고 계신가요?</p>
<p class="popup__subtext">새롭게 바뀐 지식iN Q&amp;A 페이지는 IE 9.0 이상의 브라우저에 최적화되어 있습니다. 원활한 이용을 위해 꼭 업데이트 해주세요! <a class="popup__link" href="https://support.microsoft.com/ko-kr/help/17621/internet-explorer-downloads" target="_blank">업데이트하기 <span class="sp_common ico_arr_lnk"></span></a></p>
</div>
</div>
</div>
<script type="text/javascript">
	// IE8 이하이면 브라우저 버전을 올려달라는 배너를 노출한다.
	$Fn(function() {
		var oAgent = jindo.$Agent().navigator();
		if (oAgent.ie && (oAgent.version >= 6 && oAgent.version < 9)) {
			if (typeof naver.kin.SimpleBanner !== "undefined") {
				var oIeUpdateBanner = new naver.kin.SimpleBanner({
					sBannerId: "ieUpdateBannerArea"
				});
			}
		}
	}, this).attach(document, 'domready');
</script>
<div class="header_gnb">
<div class="header_gnb_inner">
<div class="header_gnb__cell">
<h1 class="header_logo">
<a class="logo_naver" href="http://www.naver.com" onclick="nhn.Kin.Utility.nClicks('STA.naverlogo', '', '', event);" title="나의 경쟁력, 네이버"><span class="blind">NAVER</span></a>
</h1>
<div class="header_search">
<h2 class="logo_wrap">
<a class="icon_logo_kin" href="/" onclick="nhn.Kin.Utility.nClicks('STA.kin', '', '', event);"><span class="blind">지식iN</span></a>
</h2>
<h3 class="blind">검색영역</h3>
<form action="/search/list.naver" id="topSearch" method="get" name="topSearch" onsubmit="return checkQuery();">
<fieldset>
<legend>지식인 검색</legend>
<div class="search_area">
<input accesskey="s" aria-autocomplete="list" aria-controls="atcmpList" aria-expanded="false" aria-haspopup="listbox" autocomplete="off" class="search_input" id="nx_query" maxlength="255" name="query" onclick="nhn.Kin.Utility.nClicks('STA.search', '', '', event);return false;" role="combobox" title="검색어 입력" type="text" value="챗지피티"/>
<a class="search_auto" href="#">
<span class="sp_gnb icon_arrow" id="triangleBtn">자동완성 열기</span>
</a>
<div>
<iframe class="auto_complete_box" frameborder="0" height="193px" id="autoFrame" marginheight="0" marginwidth="0" scrolling="no" title="검색어 자동완성" width="290"></iframe>
</div>
<a class="search_btn" href="#" onclick="return checkQuery();"><span class="sp_gnb icon_search">지식iN 검색</span></a>
</div>
</fieldset>
</form>
</div>
</div>
<div class="header_gnb__cell">
<div class="gnb_wrap">
<div class="gnb_eXpertLogo">
<a aria-controls="bannerExpert" aria-expanded="true" aria-haspopup="true" class="link" href="https://expert.naver.com" id="bannerLink" target="_blank">
<span class="logo"><span class="blind">eXpert</span></span>
</a>
</div>
<div class="gnb_common_area">
<div id="gnb">
<script type="text/javascript">

								var gnb_service = "kin";

								var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

								var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

								var gnb_template = "gnb_utf8";

								var gnb_item_hide_option = 0;




							</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?2025052910" type="text/javascript"></script>
</div>
</div>
</div>
<div class="header__rolling rolling-notice">
<i class="icon_speaker"><span class="blind">실시간 공지사항</span></i>
<ul class="rolling-notice__list _rolling_banner" id="listNotice">
<li class="rolling-notice__item _rollingItem" data-start-time="2023-07-03 00:00:00" style="display:none;">
<a class="rolling-notice__link" href="https://m.expert.naver.com/mobile/expert/account/join/hub" onclick="nhn.Kin.Utility.nClicks('STA.event', '', '', event);">
<i class="icon_new_red _newMark" style="display:none;"><span class="blind">새소식</span></i>
<span class="text-color--secondary">지식iN은 누구나 엑스퍼트</span><br/>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
<!-- nav -->
<div class="nav" role="navigation">
<div class="nav_inner">
<h3 class="blind">메인 메뉴</h3>
<ul class="nav_list" id="au_lnb" role="menubar">
<li class="menu" role="presentation">
<a class="item" href="/index.naver" id="au_lnb_home" onclick="nhn.Kin.Utility.nClicks('LNB.home', '', '', event);" role="menuitem" tabindex="0"><em>홈</em></a>
</li>
<li class="menu" role="presentation">
<a aria-expanded="false" aria-haspopup="true" class="item" href="/qna/list.naver" onclick="nhn.Kin.Utility.nClicks('LNB.qna', '', '', event);" role="menuitem" tabindex="-1"><em>Q&amp;A</em></a>
<ul class="nav_sub_list _lnbSubMenu" role="menu">
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=11" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '11', '1', event);" role="menuitem" tabindex="-1">교육, 학문</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=1" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '1', '2', event);" role="menuitem" tabindex="-1">IT/테크</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=2" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '2', '3', event);" role="menuitem" tabindex="-1">게임</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=3" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '3', '4', event);" role="menuitem" tabindex="-1">엔터테인먼트, 예술</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=8" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '8', '5', event);" role="menuitem" tabindex="-1">생활</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=7" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '7', '6', event);" role="menuitem" tabindex="-1">건강</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=6" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '6', '7', event);" role="menuitem" tabindex="-1">사회, 정치</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=4" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '4', '8', event);" role="menuitem" tabindex="-1">경제</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=9" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '9', '9', event);" role="menuitem" tabindex="-1">여행</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=10" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '10', '10', event);" role="menuitem" tabindex="-1">스포츠, 레저</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=5" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '5', '11', event);" role="menuitem" tabindex="-1">쇼핑</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=13" onclick="nhn.Kin.Utility.nClicks('LNB.jun', '', '', event);" role="menuitem" tabindex="-1">쥬니버Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=12" onclick="nhn.Kin.Utility.nClicks('LNB.loc', '', '', event);" role="menuitem" tabindex="-1">지역&amp;플레이스</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=20" onclick="nhn.Kin.Utility.nClicks('LNB.talk', '', '', event);" role="menuitem" tabindex="-1">고민Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/opendic/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.open', '', '', event);" role="menuitem" tabindex="-1">오픈사전</a></li>
</ul>
</li>
<li class="menu" role="presentation">
<a class="item" href="/qna/questionList.naver" onclick="nhn.Kin.Utility.nClicks('LNB.answer', '', '', event);" role="menuitem" tabindex="-1"><em>답변하기</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/volunteer/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.donation', '', '', event);" role="menuitem" tabindex="-1"><em>지식기부</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/people/elite/index.naver?from=lnb" id="peopleLnbBtn" onclick="nhn.Kin.Utility.nClicks('LNB.people', '', '', event);" role="menuitem" tabindex="-1"><em>사람들</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/best/listaha.naver" onclick="nhn.Kin.Utility.nClicks('LNB.best', '', '', event);" role="menuitem" tabindex="-1"><em>베스트</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/hall/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.honor', '', '', event);" role="menuitem" tabindex="-1"><em>명예의전당</em></a>
</li>
<li class="menu" role="presentation">
<span class="lnb_bar">|</span>
<a class="item" href="/myinfo/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.profile', '', '', event);" role="menuitem" tabindex="-1"><em>프로필</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/partnercenter/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.partner', '', '', event);" role="menuitem" tabindex="-1"><em>파트너센터</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/roulette/home.naver" onclick="nhn.Kin.Utility.nClicks('LNB.roulette', '', '', event);" role="menuitem" tabindex="-1"><em>룰렛</em></a>
</li>
</ul>
<a class="nav__button_question _clickcode:LNB.q" href="#" onclick="nhn.Kin.checkRosAndGoUrl(event, '/qna/question.naver', '');sendBaLog(BaPcEventType.KIN_HOME_5048)" role="button"><span class="btn_inner"><i class="sp_gnb icon_pencil"></i>질문하기</span></a>
</div>
</div>
</div>
<script type="text/javascript">

	$Fn(function() {
		new naver.kin.LNB({
			'questionType' : ''
		});
	}).attach(window, 'load');

	var GNB_BRIGHTNESS_VALUE = {
		DARK_ICON : 0,
		DARK_ICON_AND_TRANSPARENCY : 1,
		BRIGHT_ICON_AND_TRANSPARENCY : 2,
		BRIGHT_ICON : 3
	};

	var GNB_ITEM_HIDE_OPTION_BIT_VALUE = {
		DEFAULT : 0,
		HIDE_LOGIN_BTN : 1,
		HIDE_USER_LAYER : 2,
		HIDE_NAVER_ME_AREA : 4,
		HIDE_MAIL_ALARM_AREA : 8,
		HIDE_PROFILE_IMAGE : 16,
		SHOW_BENEFIT_FOR_STAFF_MEMBER : 32
	};


	var smartSearch = "";

	var gnb_service = "kin";

	var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

	var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

	var gnb_template = "gnb_utf8";

	var gnb_item_hide_option = GNB_ITEM_HIDE_OPTION_BIT_VALUE.DEFAULT;





	$Fn(function() {

		getGNB();

		var bIsGnbClicked = false;


		$Fn(function (we) {
			if (!bIsGnbClicked) {
				gnbAllLayerClose();
			}

			bIsGnbClicked = false;
		}, this).attach(document.body, 'click');

		$Fn(function(we) {
			bIsGnbClicked = true;
		}, this).attach($('gnb'), 'click');


		try {
			$('autoFrame').src = '/static/reatcmp.html?v=4.1';
		} catch(e) {
		}

		smartSearch = new nhn.AjaxSuggestUS('nx_query', 'autoFrame', {
			url : 'https://ac.search.naver.com/nx/ac',
			cookieName : 'NaverSuggestUse',
			listbox : '_resultBox',
			sFromName : 'topSearch',
			triangleBtn : 'triangleBtn',
			sListMaxLength : 55,
			listMaxCount : 15,
			request_type : 'jsonp',
			request_data : {
				q : '{query}',
				st : '100',
				r_format : 'json',
				t_koreng : '1',
				q_enc : 'UTF-8',
				r_enc : 'UTF-8',
				r_unicode : '0',
				r_escape : '1',
				frm : 'kin'
			},
			sTriangleUpOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_up.gif',
			sTriangleUpOff : 'https://ssl.pstatic.net/sstatic/search/mypocket/v3/btn_atcmp_off_op2.gif',
			sTriangleDownOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down.gif',
			sTriangleDownOff : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down3.gif'
		}).attach({
			actSubmit : function() {
				try {
					top.selectAction(this._elForm);
				} catch(e) {
					try {
						selectAction(this._elForm);
					} catch(e) {
					}
				}

				this._elForm.submit();
			}
		});

		var expertEntryBanner = $$.getSingle("div.gnb_eXpertLogo div.banner");
		if (!!expertEntryBanner) {
			var cookie = new $Cookie();

			$Fn(function () {
				$Element(expertEntryBanner).hide();

				var newDisabledUntil = new Date().getTime() + (3 * 1000 * 24 * 60 * 60);
				cookie.set("kin_expert_entry_banner_disabled_until", newDisabledUntil, 5);
			}).attach($$.getSingle("div.gnb_eXpertLogo div.banner button.buttonCancel"), 'click');

			var disabledUntilTimestamp = new Number(cookie.get("kin_expert_entry_banner_disabled_until"));
			if (!isNaN(disabledUntilTimestamp)) {
				if (new Date().getTime() > disabledUntilTimestamp) {
					cookie.remove("kin_expert_entry_banner_disabled_until");
					$Element(expertEntryBanner).show();
				}
			} else {
				$Element(expertEntryBanner).show();
			}
		}


		if (typeof nhn.Kin.ChatMenu !== "undefined") {
			window.oChatMenu = new nhn.Kin.ChatMenu();
		}
	}).attach(window, 'load');
</script>
<div class="container-fluid" id="container">
<div class="container-fluid-content">
<div class="container-fluid-content-inner">
<div id="search_result">
<strong>'챗지피티'</strong> 에 대한 검색결과입니다.



</div>
<script type="text/javascript">
function checkAdultAuth() {
	var url = "https://" + top.location.hostname + "/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0&cs=utf8&section=kin&excludeAdultDoc=false";
	var surl = "https://" + top.location.hostname + "/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0&cs=utf8&section=kin";

	try{


			top.location.href = "https://nid.naver.com/nidlogin.login?svctype=128&a_version=2&viewtype=2&url=" + encodeURIComponent(url + "&from=search") + "&surl=" + encodeURIComponent(surl);

	} catch (e){
		history.back();
	}
}
</script>
<div class="container-fluid-content__left" id="content">
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/nhn.Kin.Search.Terms.js" type="text/javascript"></script>
<div id="s_content">
<div id="scl">
<ul>
<li class="tx_depth1"><strong><a class="_nclicks:tab.kin" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=kin" title="전체"><span>전체</span></a></strong></li>
<li class="tx_depth2"><a class="_nclicks:tab.qna" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=qna" title="Q&amp;A"><span>Q&amp;A</span></a></li>
<li class="tx_depth3"><a class="_nclicks:tab.ency" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=ency" title="오픈백과"><span>오픈백과</span></a></li>
<li>
</li></ul>
</div>
<div class="banner_suicide_stop" id="suicidalPreventionBanner" style="display:none;">
<div class="content_suicide_stop">
<h3 class="tit_suicide_stop">
<span class="blind">생명은 소중합니다.! 지금,희망을 클릭하세요.</span>
</h3>
<ul class="info_suicide_stop">
<li class="counsel_list v1">
<strong class="tit_counsel_list">전화상담</strong>
<ul class="counsel_info_list">
<li>자살예방상담전화 <em>109</em></li>
<li>정신건강상담전화 <em>1577-0199</em></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년 HelpCall</a> <em>1388</em></li>
<li><a href="https://www.lifeline.or.kr" target="_blank">한국생명의전화</a> <em>1588-9191</em></li>
<li>한마음한몸자살예방센터 <em>1577-0199</em></li>
</ul>
</li>
<li class="counsel_list v2">
<strong class="tit_counsel_list">온라인상담</strong>
<ul class="counsel_info_list">
<li><a href="https://www.lifeline.or.kr" id="btn_suicide_stop" target="_blank">한국생명의전화</a></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년사이버상담센터</a></li>
</ul>
</li>
<li class="counsel_list v3">
<strong class="tit_counsel_list">지식iN도 여러분을 돕습니다.</strong>
<ul class="counsel_info_list">
<li><a href="/qna/question.naver?expertType=doctor&amp;dirId=70109" target="_blank">의사에게질문하기</a></li>
<li><a href="/profile/index.naver?u=6oCfeacJKVQGwsBB7OHEIS4miiPixwQ%2FoueervNeYrg%3D" target="_blank">여성가족부. 한국청소년상담복지개발원</a></li>
<li><a href="/profile/index.naver?u=9xhBJX%2Fe3worDHM4Tp9d%2F4jUxoIMOWjkBn9VK4u3x8M%3D" target="_blank">경기도청소년상담복지센터</a></li>
<li class="list_aside"><a href="/profile/index.naver?u=m61fd7AyyTNGzdSXnfIARZMD2YrqU0TvSai8n3aIfHk%3D" target="_blank">마음상담</a></li>
<li><span class="counsel_vt">|</span><a href="/profile/index.naver?u=9AFcqSNT5xcmX%2BDwjqumdFA11U6ypJgxKXiNTqx%2FenU%3D" target="_blank">허그맘</a></li>
</ul>
</li>
</ul>
</div>
</div>
<script type="text/javascript">
	jindo.$Fn(function() {


		if(nhn.Kin.Utility.containSuicideKeywords('\uCC57\uC9C0\uD53C\uD2F0')) {

			jindo.$Element('suicidalPreventionBanner').show();
		}
	},this).attach(window,"load");

In [7]:
# 방법2
from urllib.request import urlopen
from urllib.parse import quote
# 챗지피티 -> %EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0
keyword = quote(keyword) # url 인코딩된 문자열로 전환
url = 'https://kin.naver.com/search/list.naver?query={}'.format(keyword)
# print(url)
response = urlopen(url)
soup = BeautifulSoup(response, #response.read()
                     'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta contents="always" name="referrer"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." name="description">
<meta content="width=1024" name="viewport"/>
<meta content="none" name="msapplication-config">
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/components.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/other.css" rel="stylesheet" type="text/css"/>
<script>

	var pcDomain = "kin.naver.com";
	var pcDomainWithProtocol = "https://kin.naver.com";
	var pcKinServiceProtocol = "https";

	var mobileDomain = "m.kin.naver.com";
	var mobileDomainWithProtocol = "https://m.kin.naver.com";
	var mobileKinServiceProtocol = "https";

	var uploadDomain = "upload.kin.naver.com";
	var uploadDomainWithProtocol = "https://upload.kin.naver.com";
	var uploadKinServiceProtocol = "https";
</script>
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/kin.js" type="text/javascript"></script>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="noindex,nofollow" name="robots">
<meta content="%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0 검색결과 : 네이버 지식iN" property="og:title">
<meta content="https://kin.naver.com/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0" property="og:url"/>
<meta content="https://ssl.pstatic.net/static/kin/common/kin_thumbnail_new_w1000.png" property="og:image"/>
<meta content="%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." property="og:description"/>
<meta content="네이버 지식iN" property="og:article:author"/>
<meta content="https://kin.naver.com" property="og:article:author:url"/>
<link href="/favicon.ico?v=2.4" rel="shortcut icon" type="image/x-icon"/>
<title>
	%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0 검색결과 : 지식iN
</title>
<script type="text/javascript">

if ( typeof window.nhn  == "undefined" ) window.nhn = {};
if ( typeof window.naver  == "undefined" ) window.naver = {};
nhn.isLogin = false;
nhn.isJunior = ("N"=="Y");
nhn.isKinUser = false;
nhn.isPortableDevice = false;
nhn.jsDir = 'https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min';

var g_ssc = ("kin.search" == "") ? "kin.temp" : "kin.search";
var ccsrv="cc.naver.com";


var kinRos = {
	bIsNoticeDisplay : ("false" == "" || "false" == "false") ? false : true,
	bIsActionNoticeDisplay : ("false" == "" || "false" == "false") ? false : true

};





var standardReportPopupUrl = "https://srp2.naver.com/report";


var baUserKey = "__UNKNOWN__";
var baLogEndpoint = "https://scv-kin.io.naver.com/jackpotlog/v1/logs";
var baAbTestResult = null;
</script>
</meta></meta></meta></meta></head>
<body>
<div id="loadingIndicator" style="display:none;width:100%;height:100%;position:fixed;top:0px;left:0px;background-color:transparent;z-index:10000;">
<img alt="데이터 요청 응답 대기중" height="21" src="https://ssl.pstatic.net/static/kin/m/ico_lod2.gif" style="position:absolute;top:49%;left:49%;" width="21"/>
</div>
<div class="wrap wrap_search" id="wrap">
<div class="skip_nav header_gnb_inner">
<a class="skip" href="#gnb" onclick="nhn.Kin.Utility.skipNavigation('au_lnb_home');return false;">메인 메뉴 바로가기</a>
<a class="skip" href="#s_content" onclick="nhn.Kin.Utility.skipNavigation('s_content');return false;">본문 바로가기</a>
</div>
<div class="header_wrap">
<div aria-labelledby="ieUpdateBannerTitle" class="popup popup--header_notice" id="ieUpdateBanner" role="dialog" style="display: none;">
<h1 class="blind" id="ieUpdateBannerTitle" tabindex="0">권장 브라우저 업데이트 안내</h1>
<div class="popup__content">
<div class="popup__title">
<p class="popup__title_text"><span class="ico_alert sp_common"></span>권장 브라우저 안내</p>
</div>
<div class="popup__maintext">
<p class="popup__text">혹시 아직 인터넷 익스플로러 9.0 미만 버전을 사용하고 계신가요?</p>
<p class="popup__subtext">새롭게 바뀐 지식iN Q&amp;A 페이지는 IE 9.0 이상의 브라우저에 최적화되어 있습니다. 원활한 이용을 위해 꼭 업데이트 해주세요! <a class="popup__link" href="https://support.microsoft.com/ko-kr/help/17621/internet-explorer-downloads" target="_blank">업데이트하기 <span class="sp_common ico_arr_lnk"></span></a></p>
</div>
</div>
</div>
<script type="text/javascript">
	// IE8 이하이면 브라우저 버전을 올려달라는 배너를 노출한다.
	$Fn(function() {
		var oAgent = jindo.$Agent().navigator();
		if (oAgent.ie && (oAgent.version >= 6 && oAgent.version < 9)) {
			if (typeof naver.kin.SimpleBanner !== "undefined") {
				var oIeUpdateBanner = new naver.kin.SimpleBanner({
					sBannerId: "ieUpdateBannerArea"
				});
			}
		}
	}, this).attach(document, 'domready');
</script>
<div class="header_gnb">
<div class="header_gnb_inner">
<div class="header_gnb__cell">
<h1 class="header_logo">
<a class="logo_naver" href="http://www.naver.com" onclick="nhn.Kin.Utility.nClicks('STA.naverlogo', '', '', event);" title="나의 경쟁력, 네이버"><span class="blind">NAVER</span></a>
</h1>
<div class="header_search">
<h2 class="logo_wrap">
<a class="icon_logo_kin" href="/" onclick="nhn.Kin.Utility.nClicks('STA.kin', '', '', event);"><span class="blind">지식iN</span></a>
</h2>
<h3 class="blind">검색영역</h3>
<form action="/search/list.naver" id="topSearch" method="get" name="topSearch" onsubmit="return checkQuery();">
<fieldset>
<legend>지식인 검색</legend>
<div class="search_area">
<input accesskey="s" aria-autocomplete="list" aria-controls="atcmpList" aria-expanded="false" aria-haspopup="listbox" autocomplete="off" class="search_input" id="nx_query" maxlength="255" name="query" onclick="nhn.Kin.Utility.nClicks('STA.search', '', '', event);return false;" role="combobox" title="검색어 입력" type="text" value="%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0"/>
<a class="search_auto" href="#">
<span class="sp_gnb icon_arrow" id="triangleBtn">자동완성 열기</span>
</a>
<div>
<iframe class="auto_complete_box" frameborder="0" height="193px" id="autoFrame" marginheight="0" marginwidth="0" scrolling="no" title="검색어 자동완성" width="290"></iframe>
</div>
<a class="search_btn" href="#" onclick="return checkQuery();"><span class="sp_gnb icon_search">지식iN 검색</span></a>
</div>
</fieldset>
</form>
</div>
</div>
<div class="header_gnb__cell">
<div class="gnb_wrap">
<div class="gnb_eXpertLogo">
<a aria-controls="bannerExpert" aria-expanded="true" aria-haspopup="true" class="link" href="https://expert.naver.com" id="bannerLink" target="_blank">
<span class="logo"><span class="blind">eXpert</span></span>
</a>
</div>
<div class="gnb_common_area">
<div id="gnb">
<script type="text/javascript">

								var gnb_service = "kin";

								var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

								var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

								var gnb_template = "gnb_utf8";

								var gnb_item_hide_option = 0;




							</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?2025052910" type="text/javascript"></script>
</div>
</div>
</div>
<div class="header__rolling rolling-notice">
<i class="icon_speaker"><span class="blind">실시간 공지사항</span></i>
<ul class="rolling-notice__list _rolling_banner" id="listNotice">
<li class="rolling-notice__item _rollingItem" data-start-time="2023-07-03 00:00:00" style="display:none;">
<a class="rolling-notice__link" href="https://m.expert.naver.com/mobile/expert/account/join/hub" onclick="nhn.Kin.Utility.nClicks('STA.event', '', '', event);">
<i class="icon_new_red _newMark" style="display:none;"><span class="blind">새소식</span></i>
<span class="text-color--secondary">지식iN은 누구나 엑스퍼트</span><br/>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
<!-- nav -->
<div class="nav" role="navigation">
<div class="nav_inner">
<h3 class="blind">메인 메뉴</h3>
<ul class="nav_list" id="au_lnb" role="menubar">
<li class="menu" role="presentation">
<a class="item" href="/index.naver" id="au_lnb_home" onclick="nhn.Kin.Utility.nClicks('LNB.home', '', '', event);" role="menuitem" tabindex="0"><em>홈</em></a>
</li>
<li class="menu" role="presentation">
<a aria-expanded="false" aria-haspopup="true" class="item" href="/qna/list.naver" onclick="nhn.Kin.Utility.nClicks('LNB.qna', '', '', event);" role="menuitem" tabindex="-1"><em>Q&amp;A</em></a>
<ul class="nav_sub_list _lnbSubMenu" role="menu">
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=11" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '11', '1', event);" role="menuitem" tabindex="-1">교육, 학문</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=1" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '1', '2', event);" role="menuitem" tabindex="-1">IT/테크</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=2" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '2', '3', event);" role="menuitem" tabindex="-1">게임</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=3" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '3', '4', event);" role="menuitem" tabindex="-1">엔터테인먼트, 예술</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=8" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '8', '5', event);" role="menuitem" tabindex="-1">생활</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=7" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '7', '6', event);" role="menuitem" tabindex="-1">건강</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=6" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '6', '7', event);" role="menuitem" tabindex="-1">사회, 정치</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=4" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '4', '8', event);" role="menuitem" tabindex="-1">경제</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=9" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '9', '9', event);" role="menuitem" tabindex="-1">여행</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=10" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '10', '10', event);" role="menuitem" tabindex="-1">스포츠, 레저</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=5" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '5', '11', event);" role="menuitem" tabindex="-1">쇼핑</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=13" onclick="nhn.Kin.Utility.nClicks('LNB.jun', '', '', event);" role="menuitem" tabindex="-1">쥬니버Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=12" onclick="nhn.Kin.Utility.nClicks('LNB.loc', '', '', event);" role="menuitem" tabindex="-1">지역&amp;플레이스</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=20" onclick="nhn.Kin.Utility.nClicks('LNB.talk', '', '', event);" role="menuitem" tabindex="-1">고민Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/opendic/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.open', '', '', event);" role="menuitem" tabindex="-1">오픈사전</a></li>
</ul>
</li>
<li class="menu" role="presentation">
<a class="item" href="/qna/questionList.naver" onclick="nhn.Kin.Utility.nClicks('LNB.answer', '', '', event);" role="menuitem" tabindex="-1"><em>답변하기</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/volunteer/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.donation', '', '', event);" role="menuitem" tabindex="-1"><em>지식기부</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/people/elite/index.naver?from=lnb" id="peopleLnbBtn" onclick="nhn.Kin.Utility.nClicks('LNB.people', '', '', event);" role="menuitem" tabindex="-1"><em>사람들</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/best/listaha.naver" onclick="nhn.Kin.Utility.nClicks('LNB.best', '', '', event);" role="menuitem" tabindex="-1"><em>베스트</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/hall/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.honor', '', '', event);" role="menuitem" tabindex="-1"><em>명예의전당</em></a>
</li>
<li class="menu" role="presentation">
<span class="lnb_bar">|</span>
<a class="item" href="/myinfo/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.profile', '', '', event);" role="menuitem" tabindex="-1"><em>프로필</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/partnercenter/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.partner', '', '', event);" role="menuitem" tabindex="-1"><em>파트너센터</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/roulette/home.naver" onclick="nhn.Kin.Utility.nClicks('LNB.roulette', '', '', event);" role="menuitem" tabindex="-1"><em>룰렛</em></a>
</li>
</ul>
<a class="nav__button_question _clickcode:LNB.q" href="#" onclick="nhn.Kin.checkRosAndGoUrl(event, '/qna/question.naver', '');sendBaLog(BaPcEventType.KIN_HOME_5048)" role="button"><span class="btn_inner"><i class="sp_gnb icon_pencil"></i>질문하기</span></a>
</div>
</div>
</div>
<script type="text/javascript">

	$Fn(function() {
		new naver.kin.LNB({
			'questionType' : ''
		});
	}).attach(window, 'load');

	var GNB_BRIGHTNESS_VALUE = {
		DARK_ICON : 0,
		DARK_ICON_AND_TRANSPARENCY : 1,
		BRIGHT_ICON_AND_TRANSPARENCY : 2,
		BRIGHT_ICON : 3
	};

	var GNB_ITEM_HIDE_OPTION_BIT_VALUE = {
		DEFAULT : 0,
		HIDE_LOGIN_BTN : 1,
		HIDE_USER_LAYER : 2,
		HIDE_NAVER_ME_AREA : 4,
		HIDE_MAIL_ALARM_AREA : 8,
		HIDE_PROFILE_IMAGE : 16,
		SHOW_BENEFIT_FOR_STAFF_MEMBER : 32
	};


	var smartSearch = "";

	var gnb_service = "kin";

	var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

	var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

	var gnb_template = "gnb_utf8";

	var gnb_item_hide_option = GNB_ITEM_HIDE_OPTION_BIT_VALUE.DEFAULT;





	$Fn(function() {

		getGNB();

		var bIsGnbClicked = false;


		$Fn(function (we) {
			if (!bIsGnbClicked) {
				gnbAllLayerClose();
			}

			bIsGnbClicked = false;
		}, this).attach(document.body, 'click');

		$Fn(function(we) {
			bIsGnbClicked = true;
		}, this).attach($('gnb'), 'click');


		try {
			$('autoFrame').src = '/static/reatcmp.html?v=4.1';
		} catch(e) {
		}

		smartSearch = new nhn.AjaxSuggestUS('nx_query', 'autoFrame', {
			url : 'https://ac.search.naver.com/nx/ac',
			cookieName : 'NaverSuggestUse',
			listbox : '_resultBox',
			sFromName : 'topSearch',
			triangleBtn : 'triangleBtn',
			sListMaxLength : 55,
			listMaxCount : 15,
			request_type : 'jsonp',
			request_data : {
				q : '{query}',
				st : '100',
				r_format : 'json',
				t_koreng : '1',
				q_enc : 'UTF-8',
				r_enc : 'UTF-8',
				r_unicode : '0',
				r_escape : '1',
				frm : 'kin'
			},
			sTriangleUpOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_up.gif',
			sTriangleUpOff : 'https://ssl.pstatic.net/sstatic/search/mypocket/v3/btn_atcmp_off_op2.gif',
			sTriangleDownOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down.gif',
			sTriangleDownOff : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down3.gif'
		}).attach({
			actSubmit : function() {
				try {
					top.selectAction(this._elForm);
				} catch(e) {
					try {
						selectAction(this._elForm);
					} catch(e) {
					}
				}

				this._elForm.submit();
			}
		});

		var expertEntryBanner = $$.getSingle("div.gnb_eXpertLogo div.banner");
		if (!!expertEntryBanner) {
			var cookie = new $Cookie();

			$Fn(function () {
				$Element(expertEntryBanner).hide();

				var newDisabledUntil = new Date().getTime() + (3 * 1000 * 24 * 60 * 60);
				cookie.set("kin_expert_entry_banner_disabled_until", newDisabledUntil, 5);
			}).attach($$.getSingle("div.gnb_eXpertLogo div.banner button.buttonCancel"), 'click');

			var disabledUntilTimestamp = new Number(cookie.get("kin_expert_entry_banner_disabled_until"));
			if (!isNaN(disabledUntilTimestamp)) {
				if (new Date().getTime() > disabledUntilTimestamp) {
					cookie.remove("kin_expert_entry_banner_disabled_until");
					$Element(expertEntryBanner).show();
				}
			} else {
				$Element(expertEntryBanner).show();
			}
		}


		if (typeof nhn.Kin.ChatMenu !== "undefined") {
			window.oChatMenu = new nhn.Kin.ChatMenu();
		}
	}).attach(window, 'load');
</script>
<div class="container-fluid" id="container">
<div class="container-fluid-content">
<div class="container-fluid-content-inner">
<div id="search_result">
<strong>'%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0'</strong> 에 대한 검색결과입니다.



</div>
<script type="text/javascript">
function checkAdultAuth() {
	var url = "https://" + top.location.hostname + "/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0&cs=utf8&section=kin&excludeAdultDoc=false";
	var surl = "https://" + top.location.hostname + "/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0&cs=utf8&section=kin";

	try{


			top.location.href = "https://nid.naver.com/nidlogin.login?svctype=128&a_version=2&viewtype=2&url=" + encodeURIComponent(url + "&from=search") + "&surl=" + encodeURIComponent(surl);

	} catch (e){
		history.back();
	}
}
</script>
<div class="container-fluid-content__left" id="content">
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/nhn.Kin.Search.Terms.js" type="text/javascript"></script>
<div id="s_content">
<div id="scl">
<ul>
<li class="tx_depth1"><strong><a class="_nclicks:tab.kin" href="/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0§ion=kin" title="전체"><span>전체</span></a></strong></li>
<li class="tx_depth2"><a class="_nclicks:tab.qna" href="/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0§ion=qna" title="Q&amp;A"><span>Q&amp;A</span></a></li>
<li class="tx_depth3"><a class="_nclicks:tab.ency" href="/search/list.naver?query=%25EC%25B1%2597%25EC%25A7%2580%25ED%2594%25BC%25ED%258B%25B0§ion=ency" title="오픈백과"><span>오픈백과</span></a></li>
<li>
</li></ul>
</div>
<div class="banner_suicide_stop" id="suicidalPreventionBanner" style="display:none;">
<div class="content_suicide_stop">
<h3 class="tit_suicide_stop">
<span class="blind">생명은 소중합니다.! 지금,희망을 클릭하세요.</span>
</h3>
<ul class="info_suicide_stop">
<li class="counsel_list v1">
<strong class="tit_counsel_list">전화상담</strong>
<ul class="counsel_info_list">
<li>자살예방상담전화 <em>109</em></li>
<li>정신건강상담전화 <em>1577-0199</em></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년 HelpCall</a> <em>1388</em></li>
<li><a href="https://www.lifeline.or.kr" target="_blank">한국생명의전화</a> <em>1588-9191</em></li>
<li>한마음한몸자살예방센터 <em>1577-0199</em></li>
</ul>
</li>
<li class="counsel_list v2">
<strong class="tit_counsel_list">온라인상담</strong>
<ul class="counsel_info_list">
<li><a href="https://www.lifeline.or.kr" id="btn_suicide_stop" target="_blank">한국생명의전화</a></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년사이버상담센터</a></li>
</ul>
</li>
<li class="counsel_list v3">
<strong class="tit_counsel_list">지식iN도 여러분을 돕습니다.</strong>
<ul class="counsel_info_list">
<li><a href="/qna/question.naver?expertType=doctor&amp;dirId=70109" target="_blank">의사에게질문하기</a></li>
<li><a href="/profile/index.naver?u=6oCfeacJKVQGwsBB7OHEIS4miiPixwQ%2FoueervNeYrg%3D" target="_blank">여성가족부. 한국청소년상담복지개발원</a></li>
<li><a href="/profile/index.naver?u=9xhBJX%2Fe3worDHM4Tp9d%2F4jUxoIMOWjkBn9VK4u3x8M%3D" target="_blank">경기도청소년상담복지센터</a></li>
<li class="list_aside"><a href="/profile/index.naver?u=m61fd7AyyTNGzdSXnfIARZMD2YrqU0TvSai8n3aIfHk%3D" target="_blank">마음상담</a></li>

#### 페이징 포함(keyword를 page수 만큼 검색한 결과를 데이터 프레임에 할당)

In [16]:
# 페이징 포함(keyword를 page수 만큼 검색한 결과를 데이터 프레임에 할당)
import requests
from bs4 import BeautifulSoup
import pandas as pd

keyword = '챗지피티'
pages = 3
items_list = [] #크롤링한 데이터를 담을 list(2차원 list)

for page in range(1, pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
#     print(url)
#     해당 url의 soup객체 -> 글제목, link를 가져와서 items_list에 append
    response = requests.get(url)
#     print(response.status_code) 정상 접근 가능한지 여부
    soup = BeautifulSoup(response.text, 'html.parser')
    items = soup.select('dt > a')
    
    for item in items:
        items_list.append([item.text, item.attrs.get('href')])
#         items_list.append({
#             'title':item.text,
#             'link':item.attrs.get('href')
#         })
        
# print(len(items_list), '개 데이터')
# print(items_list[:2])
df = pd.DataFrame(items_list, columns=['title', 'link'])
df

30 개 데이터
[['챗지피티 사주', 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31501&docId=484827506&qb=7LGX7KeA7ZS87Yuw&enc=utf8'], ['챗지피티 타로', 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31503&docId=484836001&qb=7LGX7KeA7ZS87Yuw&enc=utf8']]

,title,link
0,챗지피티 사주,https://kin.naver.com/qna/detail.naver?d1id=3&...
1,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
2,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
3,챗지피티 갸륵체 어떻게 생각하시나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
4,챗지피티 사용하려면 어떻게 해야 하나요?,https://kin.naver.com/qna/detail.naver?d1id=4&...
5,챗지피티 잡아내는거..,https://kin.naver.com/qna/detail.naver?d1id=4&...
6,챗지피티 개인정보,https://kin.naver.com/qna/detail.naver?d1id=1&...
7,챗지피티 돈 내면서 쓰는거 좋나요?,https://kin.naver.com/qna/detail.naver?d1id=6&...
8,카피킬러 표절 및 챗지피티 검사 83%,https://kin.naver.com/qna/detail.naver?d1id=11...
9,챗지피티 무료 렉 거림,https://kin.naver.com/qna/detail.naver?d1id=1&...
10,아 ㅆ 지식인 챗지피티 돌리는 것들 잘...,https://kin.naver.com/qna/detail.naver?d1id=8&...
11,챗지피티 동시 접속 되나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
12,챗지피티 plus 파일 생성 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
13,무료 챗지피티 써보려고 하는데,https://kin.naver.com/qna/detail.naver?d1id=1&...
14,하 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=11...
15,챗지피티 연애상담,https://kin.naver.com/qna/detail.naver?d1id=7&...
16,챗지피티 코딩,https://kin.naver.com/qna/detail.naver?d1id=1&...
17,퍼플렉시티 챗지피티 질문,https://kin.naver.com/qna/detail.naver?d1id=1&...
18,챗지피티 음성,https://kin.naver.com/qna/detail.naver?d1id=4&...
19,조선왕조실록 챗지피티 사실 검증,https://kin.naver.com/qna/detail.naver?d1id=11...
20,겜스고 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=1&...
21,챗지피티 검사기,https://kin.naver.com/qna/detail.naver?d1id=3&...
22,챗지피티 메모리,https://kin.naver.com/qna/detail.naver?d1id=5&...
23,챗지피티 유료 차이,https://kin.naver.com/qna/detail.naver?d1id=1&...
24,모바일 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=2&...
25,지식인<<<챗지피티,https://kin.naver.com/qna/detail.naver?d1id=7&...
26,챗지피티 결제 플러스,https://kin.naver.com/qna/detail.naver?d1id=1&...
27,챗지피티 4o 이용해야 하나…?,https://kin.naver.com/qna/detail.naver?d1id=1&...
28,챗지피티 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
29,챗지피티 주 사용 연령층,https://kin.naver.com/qna/detail.naver?d1id=1&...

In [18]:
# 페이징 포함(keyword를 page수 만큼 검색한 결과를 데이터 프레임에 할당)
# find함수사용
import requests
from bs4 import BeautifulSoup
import pandas as pd

keyword = '챗지피티'
pages = 3
items_list = [] #크롤링한 데이터를 담을 list(2차원 list)

for page in range(1, pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
#     print(url)
#     해당 url의 soup객체 -> 글제목, link를 가져와서 items_list에 append
    response = requests.get(url)
#     print(response.status_code) 정상 접근 가능한지 여부
    soup = BeautifulSoup(response.text, 'html.parser')
    dts = soup.find_all('dt')
    
    for dt in dts:
        item = dt.find('a')
        items_list.append([item.text, item.attrs.get('href')])
#         items_list.append({
#             'title':item.text,
#             'link':item.attrs.get('href')
#         })
        
# print(len(items_list), '개 데이터')
# print(items_list[:2])
df = pd.DataFrame(items_list, columns=['title', 'link'])
df

,title,link
0,챗지피티 사주,https://kin.naver.com/qna/detail.naver?d1id=3&...
1,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
2,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
3,챗지피티 갸륵체 어떻게 생각하시나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
4,챗지피티 사용하려면 어떻게 해야 하나요?,https://kin.naver.com/qna/detail.naver?d1id=4&...
5,챗지피티 잡아내는거..,https://kin.naver.com/qna/detail.naver?d1id=4&...
6,챗지피티 개인정보,https://kin.naver.com/qna/detail.naver?d1id=1&...
7,챗지피티 돈 내면서 쓰는거 좋나요?,https://kin.naver.com/qna/detail.naver?d1id=6&...
8,카피킬러 표절 및 챗지피티 검사 83%,https://kin.naver.com/qna/detail.naver?d1id=11...
9,챗지피티 무료 렉 거림,https://kin.naver.com/qna/detail.naver?d1id=1&...
10,아 ㅆ 지식인 챗지피티 돌리는 것들 잘...,https://kin.naver.com/qna/detail.naver?d1id=8&...
11,챗지피티 동시 접속 되나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
12,챗지피티 plus 파일 생성 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
13,무료 챗지피티 써보려고 하는데,https://kin.naver.com/qna/detail.naver?d1id=1&...
14,하 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=11...
15,챗지피티 연애상담,https://kin.naver.com/qna/detail.naver?d1id=7&...
16,챗지피티 코딩,https://kin.naver.com/qna/detail.naver?d1id=1&...
17,퍼플렉시티 챗지피티 질문,https://kin.naver.com/qna/detail.naver?d1id=1&...
18,챗지피티 음성,https://kin.naver.com/qna/detail.naver?d1id=4&...
19,조선왕조실록 챗지피티 사실 검증,https://kin.naver.com/qna/detail.naver?d1id=11...
20,겜스고 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=1&...
21,챗지피티 검사기,https://kin.naver.com/qna/detail.naver?d1id=3&...
22,챗지피티 메모리,https://kin.naver.com/qna/detail.naver?d1id=5&...
23,챗지피티 유료 차이,https://kin.naver.com/qna/detail.naver?d1id=1&...
24,모바일 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=2&...
25,지식인<<<챗지피티,https://kin.naver.com/qna/detail.naver?d1id=7&...
26,챗지피티 결제 플러스,https://kin.naver.com/qna/detail.naver?d1id=1&...
27,챗지피티 4o 이용해야 하나…?,https://kin.naver.com/qna/detail.naver?d1id=1&...
28,챗지피티 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
29,챗지피티 주 사용 연령층,https://kin.naver.com/qna/detail.naver?d1id=1&...

#### 함수 키워드를 페이지수만큼 검색한 결과를 데이터프레임으로 리턴

In [19]:
# 함수(keyword를 page수 만큼 검색한 결과를 데이터 프레임에 할당)
def get_items_data(keyword, pages):
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd

    items_list = [] #크롤링한 데이터를 담을 list(2차원 list)

    for page in range(1, pages+1):
        url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
    #     해당 url의 soup객체 -> 글제목, link를 가져와서 items_list에 append
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        dts = soup.find_all('dt')

        for dt in dts:
            item = dt.find('a')
            items_list.append([item.text, item.attrs.get('href')])
            
    return pd.DataFrame(items_list, columns=['title', 'link'])

In [21]:
df = get_items_data('청바지',3)
df.head(2)

                      title                                               link
0          영어로 청바지를 뭐라고하나요?  https://kin.naver.com/qna/detail.naver?d1id=11...
1  전 남자인데, 누워서 청바지를 입으면...   https://kin.naver.com/qna/detail.naver?d1id=7&...

### 6) 네이버 지식인으로 검색(openAPI 사용O)
- 특정 keyword를 특정페이지 수(3)만큼 검색한 결과 데이터프레임으로 출력
    - .env에 발급받은 키 저장 -> load (pip install python-dotenv)

In [24]:
# 환경변수를 가져오기
from dotenv import load_dotenv
import os
load_dotenv() #dotenv_path='.env' 기본값 생략가능
# print(os.getenv('Client_ID'))
# print(os.getenv('Client_Secret'))
# print(os.getenv('key'))
# print(os.getenv('key_bus'))
# print(os.getenv('key_train'))

bT7ctjQcsaRNLUAu85bK
HyWavVuxdp
ZS3iEVZ82iG9dvZc3urYq03YK9x0dwPWsaXcaNd1XACv8yWys1TONILRRSHiRNyrFo1qVk379RdHIUhAtRaL5w%3D%3D
Sg1QxDVRQ0sct0g%2BbgExvcMREqvrpT4Q3jVUHEQchy%2B71N8fDfQE604WFfnjCvy1Qv%2BUWvTOjc0z%2BYvDIJG2hQ%3D%3D
Sg1QxDVRQ0sct0g%2BbgExvcMREqvrpT4Q3jVUHEQchy%2B71N8fDfQE604WFfnjCvy1Qv%2BUWvTOjc0z%2BYvDIJG2hQ%3D%3D

In [27]:
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
encText = urllib.parse.quote("챗지피티")
# url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과(블로그)
url = "https://openapi.naver.com/v1/search/kin.json?query=" + encText # JSON 결과(지식인)
# url = "https://openapi.naver.com/v1/search/kin.xml?query=" + encText # XML 결과(지식인)
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과(블로그)

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)

response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(type(response_body.decode('utf-8')))
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

<class 'str'>
{
	"lastBuildDate":"Thu, 29 May 2025 12:12:19 +0900",
	"total":23318,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"<b>챗지피티<\/b> 사주",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=3&dirId=31501&docId=484827506&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"책지피티 사주 다 정확하지는 않죠?ㅠ 좋아하던 사람한테 연락올 가능성... <b>챗지피티<\/b>는 이용하지 않는게 좋습니다 <b>챗지피티<\/b> 제작 초기 최초 적용, 입력한... <b>챗지피티<\/b>는 세월이 갈수록 세련되어 지는게 아니라 엉뚱한 소리를 하게 되는... "
		},
		{
			"title":"<b>챗지피티<\/b> 타로",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=3&dirId=31503&docId=484836001&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"<b>챗지피티<\/b> 타로 믿을만한가요?ㅜㅜ <b>챗지피티<\/b> 타로, 그러니까 인공지능이... 요즘엔 온라인에서 너무나 손쉽게 타로를 볼 수 있고, 특히 <b>챗지피티<\/b>처럼 최신... 이런 부분은 <b>챗지피티<\/b> 같은 인공지능이 잡아내기는 어렵습니다. 인공지능 타로는... "
		},
		{
			"title":"<b>챗지피티<\/b> 타로",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=3&dirId=31503&docId=485464963&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"제가 <b>챗지피티<\/b>로 사주랑 타로를 많이 보는데요 사주는 가끔 가다가 말이 너무 달라지고요 타로도 제가 카드 뽑고... <b>챗지피티<\/b>가 해석해주는데 것도 말이 달라요 그래서 제가 똑바로 해석하라고 해서 다시 해줬는데 아예... "
		},
		{
			"title":"<b>챗지피티<\/b> 갸륵체 어떻게 생각하시나요?",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=113&docId=485266256&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"요즘 <b>챗지피티<\/b> 갸륵체가 정말 핫하더라고요. 갸륵체 외에도 다양한 사람들... 혹시 여러분은 자신만의 <b>챗지피티<\/b> 답변 문체가 있나요? 아니면 갸륵체를... 요즘 <b>챗지피티<\/b> ‘갸륵체’처럼 독특한 문체가 인기를 끌고 있다는 건, 사람들이... "
		},
		{
			"title":"<b>챗지피티<\/b> 사용하려면 어떻게 해야 하나요?",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=4&dirId=408&docId=485386619&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"<b>챗지피티<\/b> 사용하려면 어떻게 해야 하나요? 회원가입을 해야 하나요? 순서도 모르겠고 어떻게 해야 하는지 몰라... <b>챗지피티<\/b> 쓰려면 openai.com 가서 회원가입 먼저 하셔야 해요 이메일 인증하고 로그인하면 바로 질문할 수 있어요... "
		},
		{
			"title":"<b>챗지피티<\/b> 잡아내는거..",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=4&dirId=40608&docId=484141621&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"... <b>챗지피티<\/b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티<\/b>... <b>챗지피티<\/b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티<\/b>... "
		},
		{
			"title":"<b>챗지피티<\/b> 개인정보",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=11003&docId=485467804&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"<b>챗지피티<\/b>에서 지금까지 운영자가 보는거 제외하고 타인에게 개인정보가 유출된 사례가 존재하나요? 메일주소나 ip주소 등등 <b>챗지피티<\/b>의 개인정보 유출 사례가 있습니다. <b>챗지피티<\/b> 개인정보 유출과 관련된 사례는 아래... "
		},
		{
			"title":"<b>챗지피티<\/b> 해킹, 원격조종",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=11001&docId=485270801&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"<b>챗지피티<\/b> 어플을 사용하는데 오래 사용하다보면 타자가... <b>챗지피티<\/b> 앱을 사용하시다가 키보드가 제대로... 앱 오류: <b>챗지피티<\/b> 앱이 가끔 오류를 일으킬 수 있어요.... <b>챗지피티<\/b>는 OpenAI가 제공하는 신뢰할 수 있는 서비스이기... "
		},
		{
			"title":"<b>챗지피티<\/b> 돈 내면서 쓰는거 좋나요?",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=6&dirId=60101&docId=480556548&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"... <b>챗 지피티<\/b> 싸게 이용하는 방법 안내해드릴께요! 겜스고라는 사이트가시면 다른분들이랑 같이 구독해서 저렴하게 이용할수 있는데 프로모션 코드에 MLWYX입력하시면 추가할인되어요! 프로모션 코드 MLWYX 아래 ⬇️ 글 참고하세요"
		},
		{
			"title":"카피킬러 표절 및 <b>챗지피티<\/b> 검사 83%",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=11&dirId=110501&docId=484520422&qb=7LGX7KeA7ZS87Yuw&enc=utf8",
			"description":"카피킬러 사용해서 표절률이랑 <b>챗지피티<\/b>? 검사 했는데 83%나오는데 왜 이런가요?? <b>챗지피티<\/b> 유료라 사용도 안해봤는데… 맞아요. 카피킬러에서 AI(<b>챗지피티<\/b>) 판별은 원래 높게 나오는 경우 많아요. GPT 안 써도, 말투가 단정하거나... "
		}
	]
}

In [29]:
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request
import json
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
encText = urllib.parse.quote("챗지피티")
# url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과(블로그)
url = "https://openapi.naver.com/v1/search/kin.json?query=" + encText # JSON 결과(지식인)
# url = "https://openapi.naver.com/v1/search/kin.xml?query=" + encText # XML 결과(지식인)
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과(블로그)

headers = {
    'X-Naver-Client-Id':client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)

response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(type(response_body.decode('utf-8')))
    data = json.loads(response_body.decode('utf-8')) # json 형태의 str을 딕셔너리
    print(type(data))
#     print(data['items'])
else:
    print("Error Code:" + rescode)

<class 'str'>
<class 'dict'>
[{'title': '<b>챗지피티</b> 사주', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31501&docId=484827506&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '책지피티 사주 다 정확하지는 않죠?ㅠ 좋아하던 사람한테 연락올 가능성... <b>챗지피티</b>는 이용하지 않는게 좋습니다 <b>챗지피티</b> 제작 초기 최초 적용, 입력한... <b>챗지피티</b>는 세월이 갈수록 세련되어 지는게 아니라 엉뚱한 소리를 하게 되는... '}, {'title': '<b>챗지피티</b> 타로', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31503&docId=484836001&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 타로 믿을만한가요?ㅜㅜ <b>챗지피티</b> 타로, 그러니까 인공지능이... 요즘엔 온라인에서 너무나 손쉽게 타로를 볼 수 있고, 특히 <b>챗지피티</b>처럼 최신... 이런 부분은 <b>챗지피티</b> 같은 인공지능이 잡아내기는 어렵습니다. 인공지능 타로는... '}, {'title': '<b>챗지피티</b> 타로', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31503&docId=485464963&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '제가 <b>챗지피티</b>로 사주랑 타로를 많이 보는데요 사주는 가끔 가다가 말이 너무 달라지고요 타로도 제가 카드 뽑고... <b>챗지피티</b>가 해석해주는데 것도 말이 달라요 그래서 제가 똑바로 해석하라고 해서 다시 해줬는데 아예... '}, {'title': '<b>챗지피티</b> 갸륵체 어떻게 생각하시나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=113&docId=485266256&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '요즘 <b>챗지피티</b> 갸륵체가 정말 핫하더라고요. 갸륵체 외에도 다양한 사람들... 혹시 여러분은 자신만의 <b>챗지피티</b> 답변 문체가 있나요? 아니면 갸륵체를... 요즘 <b>챗지피티</b> ‘갸륵체’처럼 독특한 문체가 인기를 끌고 있다는 건, 사람들이... '}, {'title': '<b>챗지피티</b> 사용하려면 어떻게 해야 하나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=4&dirId=408&docId=485386619&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 사용하려면 어떻게 해야 하나요? 회원가입을 해야 하나요? 순서도 모르겠고 어떻게 해야 하는지 몰라... <b>챗지피티</b> 쓰려면 openai.com 가서 회원가입 먼저 하셔야 해요 이메일 인증하고 로그인하면 바로 질문할 수 있어요... '}, {'title': '<b>챗지피티</b> 잡아내는거..', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=4&dirId=40608&docId=484141621&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '... <b>챗지피티</b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티</b>... <b>챗지피티</b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티</b>... '}, {'title': '<b>챗지피티</b> 개인정보', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=11003&docId=485467804&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b>에서 지금까지 운영자가 보는거 제외하고 타인에게 개인정보가 유출된 사례가 존재하나요? 메일주소나 ip주소 등등 <b>챗지피티</b>의 개인정보 유출 사례가 있습니다. <b>챗지피티</b> 개인정보 유출과 관련된 사례는 아래... '}, {'title': '<b>챗지피티</b> 해킹, 원격조종', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=11001&docId=485270801&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 어플을 사용하는데 오래 사용하다보면 타자가... <b>챗지피티</b> 앱을 사용하시다가 키보드가 제대로... 앱 오류: <b>챗지피티</b> 앱이 가끔 오류를 일으킬 수 있어요.... <b>챗지피티</b>는 OpenAI가 제공하는 신뢰할 수 있는 서비스이기... '}, {'title': '<b>챗지피티</b> 돈 내면서 쓰는거 좋나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=6&dirId=60101&docId=480556548&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '... <b>챗 지피티</b> 싸게 이용하는 방법 안내해드릴께요! 겜스고라는 사이트가시면 다른분들이랑 같이 구독해서 저렴하게 이용할수 있는데 프로모션 코드에 MLWYX입력하시면 추가할인되어요! 프로모션 코드 MLWYX 아래 ⬇️ 글 참고하세요'}, {'title': '카피킬러 표절 및 <b>챗지피티</b> 검사 83%', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=11&dirId=110501&docId=484520422&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '카피킬러 사용해서 표절률이랑 <b>챗지피티</b>? 검사 했는데 83%나오는데 왜 이런가요?? <b>챗지피티</b> 유료라 사용도 안해봤는데… 맞아요. 카피킬러에서 AI(<b>챗지피티</b>) 판별은 원래 높게 나오는 경우 많아요. GPT 안 써도, 말투가 단정하거나... '}]

### NAVER API사용 방법 1로 변경(request)

In [41]:
# keyword를 display수만큼 지식in검색 결과를 데이터프레임에 (방법1 크롤링)
import requests
import pandas as pd
import json
from dotenv import load_dotenv
import os
load_dotenv() 
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
keyword = "쳇지피티"
cnt = 30
url = f'https://openapi.naver.com/v1/search/kin.json?query={keyword}&display={cnt}'
headers = {'X-Naver-Client-Id': client_id,
           'X-Naver-Client-Secret':client_secret}
response = requests.get(url, headers=headers)
# response.status_code
# items = json.loads(response.text)['items'] : json.loads() -방법1과 방법2
items = response.json()['items'] # 방법1에서만 가능한 함수
items_list = []
for item in items:
    items_list.append([
        item.get('title').replace('<b>','').replace('</b>',''), # item['title']
        item.get('link'),
        item.get('description').replace('<b>','').replace('</b>','')
    ])
df = pd.DataFrame(items_list, columns=['title','link','description'])
df
#print(df.loc[0, 'link'])

,title,link,description
0,쳇지피티 논문 출처,https://kin.naver.com/qna/detail.naver?d1id=4&...,"쳇지피티한테 어떤 내용에 관한 논문을 요구하고, 해당... 지피티가 스스로 여러 논..."
1,쳇지피티 한도,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 무료로 쓰고 있는데 쳇지피티로 소설 하나 쓰고 있거든요 근데 한도가 초과됐...
2,쳇지피티 사용 확인 AI,https://kin.naver.com/qna/detail.naver?d1id=5&...,쳇지피티 사용 여부 확인하는 무료 AI 뭐가 있나요?? 좀 정확하고 확실한거로 알려...
3,쳇지피티 이거 뭐예요?해킹 뭐그런거 당하는거 아니죠?,https://kin.naver.com/qna/detail.naver?d1id=1&...,아니 제가 크롬을 쓰는데 자꾸 쳇지피티가 한글번역도 이상하게 되고 말도 끊기는 거예...
4,쳇지피티 ai 소라 질문이요,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 플러스 이용중이구요 어제까지만 해도 왼쪽 메뉴에 '소라' 가 있어서요 해서...
5,쳇지피티 초기화,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 대화 목록이 사라진건 아니고 맥락에 안 맞게 말하길래 한도 초과... 챗 ...
6,학교 생기부 쳇지피티,https://kin.naver.com/qna/detail.naver?d1id=4&...,학교에서 생기부를 작성할 때 쳇지피티를 그대로 배낀 보고서를 내면 대학에서 잡는다는...
7,제가 직접 쓴 자소서 쳇지피티,https://kin.naver.com/qna/detail.naver?d1id=4&...,제가 직접 제 이야기로 자소서를 쓰고 쳇지피티한테 보내고 지피티가 수정해준 내용 참...
8,쳇지피티 질문입니다.,https://kin.naver.com/qna/detail.naver?d1id=1&...,요즘 쳇지피티가 유행이길래 한번 깔아봤는데 인사조차 못알아먹는데 어떻게 하나요..?...
9,쳇지피티 채팅 문제,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티3.0 무료버전을 종종 사용합니다 제가 질문을 &quot;이번에 전시회를 할...
10,쳇지피티 뤼튼,https://kin.naver.com/qna/detail.naver?d1id=8&...,뤼튼이 쳇지피티 인가요? 아니면 유사 ai인가요? 뤼튼은 챗GPT와 유사한 AI 기...
11,쳇지피티 화면 이상,https://kin.naver.com/qna/detail.naver?d1id=1&...,어느 날 부터 쳇지피티 화면이 아래와 같이 이상하게 보입니다.ㅠㅠ 해결 방법이 있을...
12,쳇지피티 캐릭터제작입니다,https://kin.naver.com/qna/detail.naver?d1id=2&...,쳇 지피티에서 캐릭터를 제작하면 또 다른사람에게 똑같은 컨셉으로 해주나요? 요청에따...
13,솔직히 과제 쳇지피티 모르죠?,https://kin.naver.com/qna/detail.naver?d1id=11...,쌤들이 자꾸 쳇지피티 쓰면 다잡아서 점수 낮게준다던데 그걸 어떻게 구별해요? 그냥 ...
14,쳇지피티 메모리 부정적,https://kin.naver.com/qna/detail.naver?d1id=8&...,쳇지피티한테 퍼스널 컬러 분석 겸 얼굴 사진 보냈는데 칭찬해주더니만.... 메모리 ...
15,쳇지피티 댓글,https://kin.naver.com/qna/detail.naver?d1id=8&...,이거 이런 식으로 댓글 달리는거 쳇지피티에서 찾은건가요? 저런거 딱봐도 질문 복붙해...
16,쳇지피티 말 바꿈,https://kin.naver.com/qna/detail.naver?d1id=1&...,너무 답답하고 저 같은 현상 겪으신 분들이 안 보여 지식인 써보아요 지피티에 어떤 ...
17,쳇지피티 사주,https://kin.naver.com/qna/detail.naver?d1id=3&...,정확한건가요? 이게 뭔 말인지 몇월몇시 몇년 몇일인지좀 알려주세요 이게 존재하지 않...
18,쳇지피티 용량 문제?,https://kin.naver.com/qna/detail.naver?d1id=1&...,채팅에 첨부 파일이 있으므로 계속하려면 gpt-4 뭐시기 필요하다면서 5시간 후 한...
19,쳇지피티 계정 삭제하면 구독 끝나요?,https://kin.naver.com/qna/detail.naver?d1id=4&...,안녕하세요 제가 아는 분 쳇지피티를 대신 결제 해줘서 그 분 계정에 제 체크카드를 ...
20,대학 과제 쳇지피티 저작권,https://kin.naver.com/qna/detail.naver?d1id=6&...,대학 과제 인터넷 같은거 좀 많이 보고 쓰면 무슨 위반법?? 저작권에 걸린다 하잖아...
21,쳇지피티 이거 왜이래요,https://kin.naver.com/qna/detail.naver?d1id=8&...,고치는 방법좀 알려주세요 다시하기누르시고요.안돼면 다른채팅치셨다가 다시 원래하려던걸...
22,쳇지피티 무슨앱,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티로 다들 숙제하던데 무슴앱 깔아야되나요 무료로요 자세이 알려주새요 ㅜ 숙제를...
23,쳇지피티 무료 한계,https://kin.naver.com/qna/detail.naver?d1id=1&...,쓰다보니까 한계에 도달했다면서 플러스로 업그레이드 하라는데.. X 누르니까 사라지긴...
24,유튜브 채널 이름 추천 (쳇지피티 제외),https://kin.naver.com/qna/detail.naver?d1id=1&...,유튜브 채널을 가입하려고 하는데 이름은 김은율이고 쳇지피티에 도움을 요청했는데 너무...
25,쳇지피티 수식답변 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 4o사용 중인데 원래는 수식 관련 질문하면 코드로 만들로 자동으로 변환해서...
26,쳇지피티 업로드 한도,https://kin.naver.com/qna/detail.naver?d1id=3&...,쳇지피티를 사용하고 있는데 사진을 올리려고 하는데 업로드한도를 다썼다고 하는데 어쩌...
27,쳇지피티 영수증,https://kin.naver.com/qna/detail.naver?d1id=4&...,법카로 쳇지피티 결제햇는데 결제영수증 어디서 출력할 수 있나요 아무리 찾아도 안나오...
28,쳇지피티 사용량 상한,https://kin.naver.com/qna/detail.naver?d1id=6&...,쳇 지피티를 4버전을 결제하여 사용하는데 계속 몇번 질문하면 사용량 상한에 도달했다...
29,스마트폰에서 쳇지피티 한국어로 사용하기 좋은 앱...,https://kin.naver.com/qna/detail.naver?d1id=1&...,한국어로 사용하기 좋은 쳇지피티 앱을 소개해주세요 한국어로 사용하기 좋은 쳇지피티 ...

#### 네이버 지식인 함수만들기

In [42]:
# 함수 작성
def get_naver_kin(keyword, cnt):
    import requests
    import pandas as pd
    import json
    from dotenv import load_dotenv
    import os
    load_dotenv() 
    client_id = os.getenv('Client_ID')
    client_secret = os.getenv('Client_Secret')

    url = f'https://openapi.naver.com/v1/search/kin.json?query={keyword}&display={cnt}'
    headers = {'X-Naver-Client-Id': client_id,
               'X-Naver-Client-Secret':client_secret}
    response = requests.get(url, headers=headers)

    # items = json.loads(response.text)['items'] : json.loads() -방법1과 방법2
    items = response.json()['items'] # 방법1에서만 가능한 함수
    items_list = []
    for item in items:
        items_list.append([
            item.get('title').replace('<b>','').replace('</b>',''), # item['title']
            item.get('link'),
            item.get('description').replace('<b>','').replace('</b>','')
        ])
    return pd.DataFrame(items_list, columns=['title','link','description'])

In [43]:
get_naver_kin('감자', 20)

,title,link,description
0,당뇨 감자 먹는거 안 좋나요?(서울 당뇨 감자),https://kin.naver.com/qna/detail.naver?d1id=7&...,서울 50대 초반/여 당뇨 감자 당뇨 감자 먹지말아야할 음식인가요? 제가 혈당이 조...
1,삶은감자 굽기,https://kin.naver.com/qna/detail.naver?d1id=8&...,... 삶은감자 껍질채 구워도 되나요?? 2. 구울때 올리브유를 두르면 다이어트에 ...
2,돼지감자+여주 차 때문일 수 있나요?,https://kin.naver.com/qna/detail.naver?d1id=7&...,2주째 집에서 돼지감자+여주 차를 물 대신 마시고... 돼지감자+여주 차가 다이어트...
3,오!감자 작명 이유,https://kin.naver.com/qna/detail.naver?d1id=8&...,오!감자 작명 이유 알려주세요 어떤 뜻으로 지으신건지 궁금해요 안녕하세요. 즐거움과...
4,감자 튀길때 기름에 거품,https://kin.naver.com/qna/detail.naver?d1id=7&...,냉동 감자를 1분 해동하고 기름에 튀길때 거품이 올라오면서... 감자를 튀길 때 기...
5,무상감자 계좌손익,https://kin.naver.com/qna/detail.naver?d1id=4&...,무상감자하면.주식수만줄어들고.계좌.평가손익은이상없나요?... 무상감자를 실시하면 주...
6,감자 껍질 먹어도 되나요?,https://kin.naver.com/qna/detail.naver?d1id=7&...,감자껍질 먹어도 되나요? 감자 껍질에는 다음과 같은 영양소가 풍부하게 함유되어 있어...
7,법인 주식을 감자나 양도 말고는 없애는 방법없나요?,https://kin.naver.com/qna/detail.naver?d1id=4&...,... 주식 감자를 해서 없애려고 하는데 현재 법인이 미처리이익잉여금이 5억정도 됩...
8,여주돼지감자차에 말린대추,https://kin.naver.com/qna/detail.naver?d1id=7&...,"여주돼지감자차에 말린대추 같이 섞어서 끓여도 좋을까요? 네, 여주돼지감자차에 말린 ..."
9,"치킨, 감자튀김 어느게 더 장건강에 안좋을까요?",https://kin.naver.com/qna/detail.naver?d1id=7&...,... 2조각하고 감자튀김 2회하고 어느게 더 장건강에 안좋을까요? 안녕하세요. 하...
10,위염에 감자..,https://kin.naver.com/qna/detail.naver?d1id=7&...,... 삶은 감자 먹어도 되나요?.. 감자가 좋은이유... 안좋은 이유...설명 부...
11,법인 유상감자 이후 법인세 문의,https://kin.naver.com/qna/detail.naver?d1id=4&...,... 줄여 감자를 진행하려고 합니다. 감자 진행이후 법인 청산시 배당소득세율이 변...
12,초록색 감자 반개 먹었어요...,https://kin.naver.com/qna/detail.naver?d1id=7&...,초록색 삶은감자 있어서 먹었는데 톡쏘고 매워서 반개 먹다가 검색해봤는데 초록색 감자...
13,구운감자 먹다가 이빨 흔들림,https://kin.naver.com/qna/detail.naver?d1id=7&...,구운감자라는 ㄱ과자 먹다가 이빨 흔들리는데 이거 어케 치과안가고 어케고쳐요 안녕하세...
14,미국 감자칩,https://kin.naver.com/qna/detail.naver?d1id=9&...,미국에서 감자칩 집 까지 배달 했줄나요? 미국인 감자를 많이 먹나요? 미국에 감자요...
15,혈압 감자칩 괜찮나요?( 혈압),https://kin.naver.com/qna/detail.naver?d1id=7&...,... 많은 감자칩이 미치는 영향을 설명해 주시겠어요? 감자칩이 혈압 수치에... ...
16,감자팩..,https://kin.naver.com/qna/detail.naver?d1id=7&...,... 1.집에서 감자팩을 하려하는데 어떻게 만드나요? 2.믹서기 있을때 감자팩 만...
17,2024.수매계약을 체결후 감자농사를 지었는데 사기,https://kin.naver.com/qna/detail.naver?d1id=6&...,... 농가에 감자값 일부를 지급하여 법적 한도금액을 면하려 하였고 피의자가 감자를...
18,코스트코 감자 뇨끼의 식감과 맛은 어떤가요?,https://kin.naver.com/qna/detail.naver?d1id=5&...,최근 코스트코에서 구매한 감자 뇨끼의 실제 식감과 맛이... 코스트코에서 판매하는 ...
19,감자 동결건조 과자 이름 찾아뇨,https://kin.naver.com/qna/detail.naver?d1id=8&...,구몬 쌤이 예전에 감자를 동결건조한 과자를... 눈을감자 아니고 좀 유명한 과자는 ...

### quiz) 네이버 open API를 이용해서 청바지 이미지 100건 데이터를 csv파일로 저장
    - 데이터 : 제목, 이미지링크, 썸네일링크, 높이, 폭

In [ ]:
import urllib.parse
word = "청바지"
word = urllib.parse.quote(word)
url = 'https://openapi.naver.com/v1/search/image?query={word}&'

In [54]:
import requests
import pandas as pd
import json
from dotenv import load_dotenv
import os
load_dotenv() 
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
keyword = "청바지"
cnt = 100
url = f'https://openapi.naver.com/v1/search/image?query={keyword}&display={cnt}'
headers = {'X-Naver-Client-Id': client_id,
           'X-Naver-Client-Secret':client_secret}
response = requests.get(url, headers=headers)
# response.status_code
# items = json.loads(response.text)['items'] : json.loads() -방법1과 방법2
items = response.json()['items'] # 방법1에서만 가능한 함수


items_list = []
for item in items:
    items_list.append([
        item.get('title'), # item['title']
        item.get('link'),
        item.get('thumbnail'),
        item.get('sizeheight'),
        item.get('sizewidth'),
    ])
df = pd.DataFrame(items_list, columns=['title','link','thumbnail','sizeheight','sizewidth'])
df

# title,link,thumbnail,sizeheight,sizewidth
# items
#print(df.loc[0, 'link'])

,title,link,thumbnail,sizeheight,sizewidth
0,BINIWU 심플 빈티지 워싱 청바지 남자 봄가을 루즈핏 통바지 28 빈티지블루,http://shopping.phinf.naver.net/main_5172227/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
1,중년 청바지 아이스 팬츠 남성 얇은 슬랙스 바지남 긴바지,http://shopping.phinf.naver.net/main_5314890/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
2,게스 게스 여성 청바지 플레어 붓컷 미디엄블루 데님팬츠 M YM3D0117,http://shopping.phinf.naver.net/main_5182791/5...,https://search.pstatic.net/common/?type=b150&s...,700,700
3,가우리 봄 가을 프리미엄 중년 남성 청바지 CRO 스판 청 팬츠 - 청바지 | 쿠팡,https://thumbnail8.coupangcdn.com/thumbnails/r...,https://search.pstatic.net/sunny/?type=b150&sr...,492,492
4,청바지 남자 여름 얇은 레져 텐셀 아메리칸 빈티지 청바지 남자 카우형 남자 스타일 팬츠,http://shopping.phinf.naver.net/main_5188539/5...,https://search.pstatic.net/common/?type=b150&s...,600,600
...,...,...,...,...,...
95,남자 블랙진 기모 가을 기모청바지 얇은 청바지,http://shopping.phinf.naver.net/main_5291012/5...,https://search.pstatic.net/common/?type=b150&s...,300,300
96,남자 청바지 타이거 자수 스판 슬림 청바지 ZT120306 28,http://shopping.phinf.naver.net/main_5289686/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
97,[쩡대샵] 남자 811원포 청바지 : 쩡대샵,http://shop1.phinf.naver.net/20180919_176/hotj...,https://search.pstatic.net/common/?type=b150&s...,640,640
98,하늘 자수 배기 팬츠 칠부 청바지 여 women s jeans 하늘비즈 A8 I09...,http://shopping.phinf.naver.net/main_5463263/5...,https://search.pstatic.net/common/?type=b150&s...,1920,1920
99,엄마옷 여성 와이드 청바지 항아리 배기바지,http://shopping.phinf.naver.net/main_5369150/5...,https://search.pstatic.net/common/?type=b150&s...,600,600

In [55]:
df.to_csv('네이버청바지100개_고정현.csv', index=False, encoding='cp949')

#### 정답

#### 사진 저장

In [78]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv() 
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
word = "청바지"
url = f'https://openapi.naver.com/v1/search/image?query={word}&display=100'
headers = {'X-Naver-Client-Id': client_id,
           'X-Naver-Client-Secret':client_secret}
response = requests.get(url, headers=headers)
# print(response.text)
items = response.json()['items'] # 방법1에서만 가능한 함수
items_list = []
for idx, item in enumerate(items):
    title = item.get('title')
    link = item.get('link')
    thumbnail = item.get('thumbnail')
    sizeheight = item.get('sizeheight')
    sizewidth = item.get('sizewidth')
    items_list.append({
        'no': idx+1,
        'title': title,
        'link' : link,
        'thumbnail' : thumbnail,
        'sizeheight':sizeheight,
        'sizewidth' :sizewidth
    })
    # link와 thumbnail을 저장
    
df = pd.DataFrame(items_list)
df

,no,title,link,thumbnail,sizeheight,sizewidth
0,1,BINIWU 심플 빈티지 워싱 청바지 남자 봄가을 루즈핏 통바지 28 빈티지블루,http://shopping.phinf.naver.net/main_5172227/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
1,2,중년 청바지 아이스 팬츠 남성 얇은 슬랙스 바지남 긴바지,http://shopping.phinf.naver.net/main_5314890/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
2,3,게스 게스 여성 청바지 플레어 붓컷 미디엄블루 데님팬츠 M YM3D0117,http://shopping.phinf.naver.net/main_5182791/5...,https://search.pstatic.net/common/?type=b150&s...,700,700
3,4,가우리 봄 가을 프리미엄 중년 남성 청바지 CRO 스판 청 팬츠 - 청바지 | 쿠팡,https://thumbnail8.coupangcdn.com/thumbnails/r...,https://search.pstatic.net/sunny/?type=b150&sr...,492,492
4,5,청바지 남자 여름 얇은 레져 텐셀 아메리칸 빈티지 청바지 남자 카우형 남자 스타일 팬츠,http://shopping.phinf.naver.net/main_5188539/5...,https://search.pstatic.net/common/?type=b150&s...,600,600
...,...,...,...,...,...,...
95,96,남자 블랙진 기모 가을 기모청바지 얇은 청바지,http://shopping.phinf.naver.net/main_5291012/5...,https://search.pstatic.net/common/?type=b150&s...,300,300
96,97,남자 청바지 타이거 자수 스판 슬림 청바지 ZT120306 28,http://shopping.phinf.naver.net/main_5289686/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
97,98,[쩡대샵] 남자 811원포 청바지 : 쩡대샵,http://shop1.phinf.naver.net/20180919_176/hotj...,https://search.pstatic.net/common/?type=b150&s...,640,640
98,99,하늘 자수 배기 팬츠 칠부 청바지 여 women s jeans 하늘비즈 A8 I09...,http://shopping.phinf.naver.net/main_5463263/5...,https://search.pstatic.net/common/?type=b150&s...,1920,1920
99,100,엄마옷 여성 와이드 청바지 항아리 배기바지,http://shopping.phinf.naver.net/main_5369150/5...,https://search.pstatic.net/common/?type=b150&s...,600,600

In [79]:
df.loc[0, 'link']

'http://shopping.phinf.naver.net/main_5172227/51722270863.20241203000649.jpg'

In [80]:
df[df['link'].str.find('?')!=-1]

Empty DataFrame
Columns: [no, title, link, thumbnail, sizeheight, sizewidth]
Index: []

In [81]:
df[~df['link'].str.endswith('jpg')].loc[5, 'link']

'http://shop1.phinf.naver.net/20250503_295/1746250611381Vinxl_JPEG/21192829047529977_2039968073.jpeg'

In [84]:
def save_img(attr, idx, query, url):
    import requests
    '{attr}_{idx}_{query}.{확장자} 이미지 저장'
    file_extension = url.split('.')[-1]
    quote_index = file_extension.find('?')
    
    if quote_index != -1:
        file_extension = file_extension[:quote_index]
    print(file_extension)
    img = requests.get(url).content
    with open(f'ch14_image/{attr}_{idx}_{query}.{file_extension}', 'wb') as f:
        f.write(img)

In [85]:
save_img('메인', 1, '청바지', df.loc[5, 'link'])

jpeg

#### # word image 100개 검색한 데이터는 csv파일로, 이미지는 ch14_image폴더에 저장되는 함수

In [89]:
# word image 100개 검색한 데이터는 csv파일로, 이미지는 ch14_image폴더에 저장되는 함수
def get_naver_save_image(word):
    import requests
    import pandas as pd
    from dotenv import load_dotenv
    import os
    load_dotenv() 
    client_id = os.getenv('Client_ID')
    client_secret = os.getenv('Client_Secret')

    url = f'https://openapi.naver.com/v1/search/image?query={word}&display=100'
    headers = {'X-Naver-Client-Id': client_id,
               'X-Naver-Client-Secret':client_secret}
    response = requests.get(url, headers=headers)

    items = response.json()['items'] # 방법1에서만 가능한 함수
    items_list = []
    for idx, item in enumerate(items):
        title = item.get('title')
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        sizeheight = item.get('sizeheight')
        sizewidth = item.get('sizewidth')
        items_list.append({
            'no': idx+1,
            'title': title,
            'link' : link,
            'thumbnail' : thumbnail,
            'sizeheight':sizeheight,
            'sizewidth' :sizewidth
        })
        # link와 thumbnail을 저장
        save_img('메인', idx+1, word, link)
        save_img('썸네일', idx+1, word, thumbnail)
        # 20%, 40%, 60%, 80% 지점에서 message 출력
        if idx/20 == round(idx/20):
            print(f'= = = {idx} % 진행 중입니다 = = =')       
    df = pd.DataFrame(items_list)
    df.to_csv(f'ch14_image/{word}.csv', index=False, encoding='cp949')
    print('~ ~ ~ 이미지 및 csv 파일 저장 완료 ~ ~ ~')

In [90]:
get_naver_save_image('청바지')

jpg
jpg
= = = 0 % 진행 중입니다 = = =
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpeg
jpeg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpeg
jpeg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
JPG
JPG
jpg
jpg
= = = 20 % 진행 중입니다 = = =
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
= = = 40 % 진행 중입니다 = = =
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
png
png
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpeg
jpeg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
= = = 60 % 진행 중입니다 = = =
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
JPG
JPG
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
= = = 80 % 진행 중입니다 = = =
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
jpg
~ ~ ~ 이미지 및 csv 파일 저장 완료 ~ ~ ~

## 2.3 xml 파일
- 기상 예측 RSS 활용
- http://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20250529.xml
- pip install lxml

In [91]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [101]:
url = 'http://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20250529.xml'
response = urlopen(url)
response.status # response.getcode()
soup = BeautifulSoup(response, 'xml') # pip install lxml
locals = soup.find_all('local_ta')
# locals[1]
items_list = []
for local in locals:
    local_ta_name = local.select_one('local_ta_name').text
    week1_normalYear = local.select_one('week1_local_ta_normalYear').text # 평년기온
    week1_local_ta_similarRange = local.select_one('week1_local_ta_similarRange').text # 기온범위
    week1_local_ta_minVal = local.select_one('week1_local_ta_minVal').text
    week1_local_ta_maxVal = local.select_one('week1_local_ta_maxVal').text
    
    week2_normalYear = local.select_one('week1_local_ta_normalYear').text # 평년기온
    week2_local_ta_similarRange = local.select_one('week1_local_ta_similarRange').text # 기온범위
    week2_local_ta_minVal = local.select_one('week1_local_ta_minVal').text
    week2_local_ta_maxVal = local.select_one('week1_local_ta_maxVal').text
    items_list.append({
        '지역':local_ta_name,
        '1주후평년기온':float(week1_normalYear),
        '1주범위':week1_local_ta_similarRange,
        '1주최저':week1_local_ta_minVal,
        '1주최고':week1_local_ta_maxVal,
        '2주후평년기온':week2_normalYear,
        '2주범위':week2_local_ta_similarRange,
        '2주최저':week2_local_ta_minVal,
        '2주최고':week2_local_ta_maxVal,
    })
df = pd.DataFrame(items_list)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   지역       13 non-null     object
 1   1주후평년기온  13 non-null     float64
 2   1주범위     13 non-null     object
 3   1주최저     13 non-null     object
 4   1주최고     13 non-null     object
 5   2주후평년기온  13 non-null     object
 6   2주범위     13 non-null     object
 7   2주최저     13 non-null     object
 8   2주최고     13 non-null     object
dtypes: float64(1), object(8)
memory usage: 1.0+ KB

# 3. 연습문제
- YES24 베스트셀러 정보를 순위, 책이름, 저자및 출판사, 가격
- ch14_yes24.csv(ch14_yes24.txt)로 출력

In [106]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

size = 48
pages = 1
items_list = []

for page in range(1, pages+1):
    url = f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize={size}'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    rank = soup.select('em.ico.rank')
    gd_name = soup.select('a.gd_name')    
    writer = soup.select('span.authPub.info_auth > a')
    price = soup.select('strong.txt_num > em.yes_b')
    company = soup.select('span.authPub.info_pub > a')

    for i in range(len(gd_name)):
        items_list.append({
            '순위': rank[i].text,
            '책이름': gd_name[i].text,
            '저자': writer[i].text,
            '출판사': company[i].text,
            '가격': price[i].text+'원',
            })

df = pd.DataFrame(items_list, columns=['순위', '책이름', '저자', '출판사', '가격',])
df

,순위,책이름,저자,출판사,가격
0,1,청춘의 독서,유시민,웅진지식하우스,"17,010원"
1,2,엄마의 말 연습,윤지영,카시오페아,"15,750원"
2,3,단 한 번의 삶,김영하,복복서가,"15,120원"
3,4,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,"18,000원"
4,5,이로운 보수 의로운 진보,최강욱,한겨레출판,"18,000원"
5,6,소년이 온다,최강혁,창비,"13,500원"
6,7,초역 부처의 말,한강,포레스트북스,"16,020원"
7,8,어른의 행복은 조용하다,코이케 류노스케,페이지2북스,"16,020원"
8,9,모순,박재현,쓰다,"11,700원"
9,10,듀얼 브레인,태수,상상스퀘어,"18,900원"
10,11,쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션),양귀자,하이스트,"15,750원"
11,12,빛과 실,이선 몰릭,문학과지성사,"13,500원"
12,13,에그박사 15,신동숙,미래엔아이세움,"14,220원"
13,14,혼모노,쇼펜하우어,창비,"16,200원"
14,15,위버멘쉬,김지민,떠오름,"16,020원"
15,16,친구 사이에도 예의가 필요해,한강,길벗스쿨,"15,300원"
16,17,급류,에그박사,민음사,"12,600원"
17,18,괴수 8호 15 트리플특장판,박송이,서울미디어코믹스(서울문화사),"5,400원"
18,19,"첫 여름, 완주",홍종현,무제,"15,300원"
19,20,친구가 상처 줄 때 똑똑하게 나를 지키는 법,주세종,한빛에듀,"15,120원"
20,21,결국 국민이 합니다,성해나,오마이북,"19,800원"
21,22,워런 버핏 웨이,프리드리히 니체,상상스퀘어,"29,700원"
22,23,서랍에 저녁을 넣어 두었다,한진아,문학과지성사,"10,800원"
23,24,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",지니 킴,이투스북,"14,850원"
24,25,설민석의 한국사 대모험 33,박혜림,단꿈아이,"12,600원"
25,26,흔한남매 19,정대건,미래엔아이세움,"14,220원"
26,27,2025 심우철 실전 동형 모의고사 Season 4,마츠모토 나오야,심슨북스,"12,960원"
27,28,최애의 아이 16 특별판,유유리,대원,"35,100원"
28,29,넥서스,김금희,김영사,"25,020원"
29,30,돈의 흐름은 되풀이된다,이현아,포르체,"17,100원"
30,31,ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC,서영,YBM(와이비엠),"17,820원"
31,32,스토너,이재명,알에이치코리아(RHK),"15,120원"
32,33,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",로버트 해그스트롬,이투스북,"14,400원"
33,34,ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC,신용우,YBM(와이비엠),"17,820원"
34,35,최애의 아이 16,한강,대원,"7,110원"
35,36,"엔비디아 젠슨 황, 생각하는 기계",최태성,알에이치코리아(RHK),"25,200원"
36,37,진짜의 마인드,설민석,터닝페이지,"16,650원"
37,38,"혹시, 돈 얘기해도 될까요?",남이담,필름,"17,820원"
38,39,너에게 들려주는 단단한 말,정현희,퍼스트펭귄,"16,200원"
39,40,질문의 격,강석화,앤의서재,"16,020원"
40,41,하루 한 장 나의 어휘력을 위한 필사 노트,흔한남매,위즈덤하우스,"21,420원"
41,42,길고양이와 늑대 5 더블특전판,백난도,학산문화사,"5,400원"
42,43,과자 사면 과학 드립니다,유난희,풀빛,"13,500원"
43,44,부의 전략 수업,흔한컴퍼니,필름,"17,820원"
44,45,살아갈 날들을 위한 괴테의 시,심우철,퍼스트펭귄,"17,100원"
45,46,2025 문동균 한국사 지방직 대비 실전 봉투모의고사,아카사카 아카,에스티유니타스,"10,800원"
46,47,똑게육아,요코야리 멘고,북로스트,"19,980원"
47,48,파과 (리커버),유발 하라리,위즈덤하우스,"14,220원"

In [109]:
df.to_csv('ch14_yes24_고정현.csv', index=False, encoding='cp949')

In [108]:
df.to_csv('ch14_yes24_고정현.txt', sep='\t', index=False)

In [ ]:
# 리스트
import requests
from bs4 import BeautifulSoup
import pandas as pd

size = 48
pages = 1
items_list = []

for page in range(1, pages+1):
    url = f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize={size}'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    rank = soup.select('em.ico.rank')
    gd_name = soup.select('a.gd_name')    
    writer = soup.select('span.authPub.info_auth > a')
    price = soup.select('strong.txt_num > em.yes_b')
    company = soup.select('span.authPub.info_pub > a')

    for i in range(len(gd_name)):
        items_list.append({
            '순위': rank[i].text,
            '책이름': gd_name[i].text,
            '저자': writer[i].text,
            '출판사': company[i].text,
            '가격': price[i].text+'원',
        })

df = pd.DataFrame(items_list, columns=['순위', '책이름', '저자', '출판사', '가격',])
df

In [113]:
# 데이터프레임으로 append (체감상 더 느린것 같음)
size = 48
pages = 1
items_list = []

for page in range(1, pages+1):
    url = f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize={size}'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    items_list = []
    for i in range(len(gd_name)):
        rank = soup.select('em.ico.rank')
        gd_name = soup.select('a.gd_name')    
        writer = soup.select('span.authPub.info_auth > a')
        price = soup.select('strong.txt_num > em.yes_b')
        company = soup.select('span.authPub.info_pub > a')

        items_list.append({
                '순위': rank[i].text,
                '책이름': gd_name[i].text,
                '저자': writer[i].text,
                '출판사': company[i].text,
                '가격': price[i].text+'원',
            })
df = pd.DataFrame(items_list)
df

,순위,책이름,저자,출판사,가격
0,1,청춘의 독서,유시민,웅진지식하우스,"17,010원"
1,2,엄마의 말 연습,윤지영,카시오페아,"15,750원"
2,3,단 한 번의 삶,김영하,복복서가,"15,120원"
3,4,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,"18,000원"
4,5,이로운 보수 의로운 진보,최강욱,한겨레출판,"18,000원"
5,6,소년이 온다,최강혁,창비,"13,500원"
6,7,초역 부처의 말,한강,포레스트북스,"16,020원"
7,8,어른의 행복은 조용하다,코이케 류노스케,페이지2북스,"16,020원"
8,9,모순,박재현,쓰다,"11,700원"
9,10,듀얼 브레인,태수,상상스퀘어,"18,900원"
10,11,쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션),양귀자,하이스트,"15,750원"
11,12,빛과 실,이선 몰릭,문학과지성사,"13,500원"
12,13,에그박사 15,신동숙,미래엔아이세움,"14,220원"
13,14,혼모노,쇼펜하우어,창비,"16,200원"
14,15,위버멘쉬,김지민,떠오름,"16,020원"
15,16,친구 사이에도 예의가 필요해,한강,길벗스쿨,"15,300원"
16,17,급류,에그박사,민음사,"12,600원"
17,18,괴수 8호 15 트리플특장판,박송이,서울미디어코믹스(서울문화사),"5,400원"
18,19,"첫 여름, 완주",홍종현,무제,"15,300원"
19,20,친구가 상처 줄 때 똑똑하게 나를 지키는 법,주세종,한빛에듀,"15,120원"
20,21,결국 국민이 합니다,성해나,오마이북,"19,800원"
21,22,워런 버핏 웨이,프리드리히 니체,상상스퀘어,"29,700원"
22,23,서랍에 저녁을 넣어 두었다,한진아,문학과지성사,"10,800원"
23,24,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",지니 킴,이투스북,"14,850원"
24,25,설민석의 한국사 대모험 33,박혜림,단꿈아이,"12,600원"
25,26,흔한남매 19,정대건,미래엔아이세움,"14,220원"
26,27,2025 심우철 실전 동형 모의고사 Season 4,마츠모토 나오야,심슨북스,"12,960원"
27,28,최애의 아이 16 특별판,유유리,대원,"35,100원"
28,29,넥서스,김금희,김영사,"25,020원"
29,30,돈의 흐름은 되풀이된다,이현아,포르체,"17,100원"
30,31,ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC,서영,YBM(와이비엠),"17,820원"
31,32,스토너,이재명,알에이치코리아(RHK),"15,120원"
32,33,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",로버트 해그스트롬,이투스북,"14,400원"
33,34,ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC,신용우,YBM(와이비엠),"17,820원"
34,35,최애의 아이 16,한강,대원,"7,110원"
35,36,"엔비디아 젠슨 황, 생각하는 기계",최태성,알에이치코리아(RHK),"25,200원"
36,37,진짜의 마인드,설민석,터닝페이지,"16,650원"
37,38,"혹시, 돈 얘기해도 될까요?",남이담,필름,"17,820원"
38,39,너에게 들려주는 단단한 말,정현희,퍼스트펭귄,"16,200원"
39,40,질문의 격,강석화,앤의서재,"16,020원"
40,41,하루 한 장 나의 어휘력을 위한 필사 노트,흔한남매,위즈덤하우스,"21,420원"
41,42,길고양이와 늑대 5 더블특전판,백난도,학산문화사,"5,400원"
42,43,과자 사면 과학 드립니다,유난희,풀빛,"13,500원"
43,44,부의 전략 수업,흔한컴퍼니,필름,"17,820원"
44,45,살아갈 날들을 위한 괴테의 시,심우철,퍼스트펭귄,"17,100원"
45,46,2025 문동균 한국사 지방직 대비 실전 봉투모의고사,아카사카 아카,에스티유니타스,"10,800원"
46,47,똑게육아,요코야리 멘고,북로스트,"19,980원"
47,48,파과 (리커버),유발 하라리,위즈덤하우스,"14,220원"