In [12]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font family: Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family: Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding top:120px;}
div.text_cell_render ul li {font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font color="red" size="5"> Untitled </font></b>

In [4]:
# 12분 08초
sum = 0
for i in range(1, 101):
    sum += i
print(sum)

5050

In [5]:
sum = 0
n = int(input("n: "))

for j in range(1, n + 1):
    for i in range(1, n + 1):
        sum += 1

print(sum)

n: 4
16

In [1]:
import time

#시작시간 기록
for i in range(1000000):
    resurt = i ** 2
    
#종료시간 기록
end_time = time.time()

In [3]:
import timeit

def test_function():
    for i in range(1000000):
        result = i ** 2
        
#실행시간 측정
execution_time = timeit.timeit(test_function, number = 1)
print(f'코드 실행시간 : {execution_time:.6f}초')

코드 실행시간 : 0.293783초

In [5]:
import itertools

iterable1 = 'ABCD'
iterable2 = 'xy'
iterable3 = '1234'
print(list(itertools.product(iterable1, iterable2, iterable3)))
a = list(itertools.product(iterable1, iterable2, iterable3))

[('A', 'x', '1'), ('A', 'x', '2'), ('A', 'x', '3'), ('A', 'x', '4'), ('A', 'y', '1'), ('A', 'y', '2'), ('A', 'y', '3'), ('A', 'y', '4'), ('B', 'x', '1'), ('B', 'x', '2'), ('B', 'x', '3'), ('B', 'x', '4'), ('B', 'y', '1'), ('B', 'y', '2'), ('B', 'y', '3'), ('B', 'y', '4'), ('C', 'x', '1'), ('C', 'x', '2'), ('C', 'x', '3'), ('C', 'x', '4'), ('C', 'y', '1'), ('C', 'y', '2'), ('C', 'y', '3'), ('C', 'y', '4'), ('D', 'x', '1'), ('D', 'x', '2'), ('D', 'x', '3'), ('D', 'x', '4'), ('D', 'y', '1'), ('D', 'y', '2'), ('D', 'y', '3'), ('D', 'y', '4')]

In [8]:
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
import random
a=("백돈","엽떡")
print(random.choice(a))

엽떡

In [2]:
a = int(input().strip())
b = int(input().strip())

print(f"a = {a}")
print(f"b = {b}")

4
5
a = 4
b = 5

# 웹크롤링

In [43]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://www.yes24.com/product/category/bestseller?CategoryNumber=001&SumGb=02&pid=123487&cosemkid=go14913756400533498&utm_source=google_pc&utm_medium=cpc&utm_campaign=book_pc&utm_content=ys_240530_google_pc_cc_book_pc_yes24&utm_term=yes24%eb%b2%a0%ec%8a%a4%ed%8a%b8%ec%85%80%eb%9f%ac&gad_source=1&gad_campaignid=57752190&gbraid=0AAAAAD79Irpn6yOBw_-tFRQGS_7tiJXNW&gclid=Cj0KCQjwxdXBBhDEARIsAAUkP6hpmfi7gQxu34Pi8dR3GuIU986DS6fi_2Wsvno21Lv0itMmYtrQlBkaAteyEALw_wcB'
response = requests.get(url)
#response, response.status_code
#response.content
#response.content.decode('cp949')
#response.text
soup = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

In [44]:
# 책제목 1페이지 24개
title = soup.select('a.gd_name')
for t in title:
    print(t.text, end='\t')

청춘의 독서	엄마의 말 연습	어른의 품격을 채우는 100일 필사 노트	단 한 번의 삶	이로운 보수 의로운 진보	소년이 온다	어른의 행복은 조용하다	초역 부처의 말	모순	빛과 실	쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션)	듀얼 브레인	괴수 8호 15 트리플특장판	길고양이와 늑대 5 더블특전판	혼모노	위버멘쉬	결국 국민이 합니다	급류	에그박사 15	첫 여름, 완주	친구가 상처 줄 때 똑똑하게 나를 지키는 법	친구 사이에도 예의가 필요해	서랍에 저녁을 넣어 두었다	워런 버핏 웨이

In [45]:
# 책가격 1페이지 24개
price = soup.select('strong.txt_num>em.yes_b')
price_num = [round(float(p.text.replace(',',''))) for p in price]

In [46]:
# 가격에 원 붙히기
prices = price_num
prices_with_won = list(map(lambda x: str(x) + "원", prices))
prices_with_won

['17010원',
 '15750원',
 '18000원',
 '15120원',
 '18000원',
 '13500원',
 '16020원',
 '16020원',
 '11700원',
 '13500원',
 '15750원',
 '18900원',
 '5400원',
 '5400원',
 '16200원',
 '16020원',
 '19800원',
 '12600원',
 '14220원',
 '15300원',
 '15120원',
 '15300원',
 '10800원',
 '29700원']

In [47]:
for idx in range(len(title)):
    print("{} : {} - {}".format(idx+1,
                                  title[idx].text,
                                 prices_with_won[idx],
                                 ))

1 : 청춘의 독서 - 17010원
2 : 엄마의 말 연습 - 15750원
3 : 어른의 품격을 채우는 100일 필사 노트 - 18000원
4 : 단 한 번의 삶 - 15120원
5 : 이로운 보수 의로운 진보 - 18000원
6 : 소년이 온다 - 13500원
7 : 어른의 행복은 조용하다 - 16020원
8 : 초역 부처의 말 - 16020원
9 : 모순 - 11700원
10 : 빛과 실 - 13500원
11 : 쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션) - 15750원
12 : 듀얼 브레인 - 18900원
13 : 괴수 8호 15 트리플특장판 - 5400원
14 : 길고양이와 늑대 5 더블특전판 - 5400원
15 : 혼모노 - 16200원
16 : 위버멘쉬 - 16020원
17 : 결국 국민이 합니다 - 19800원
18 : 급류 - 12600원
19 : 에그박사 15 - 14220원
20 : 첫 여름, 완주 - 15300원
21 : 친구가 상처 줄 때 똑똑하게 나를 지키는 법 - 15120원
22 : 친구 사이에도 예의가 필요해 - 15300원
23 : 서랍에 저녁을 넣어 두었다 - 10800원
24 : 워런 버핏 웨이 - 29700원

In [48]:
result = []
for idx in range(len(title)):
    print("{} : {} - {}".format(idx+1,
                                  title[idx].text,
                                 prices_with_won[idx],
                                 ))
result

1 : 청춘의 독서 - 17010원
2 : 엄마의 말 연습 - 15750원
3 : 어른의 품격을 채우는 100일 필사 노트 - 18000원
4 : 단 한 번의 삶 - 15120원
5 : 이로운 보수 의로운 진보 - 18000원
6 : 소년이 온다 - 13500원
7 : 어른의 행복은 조용하다 - 16020원
8 : 초역 부처의 말 - 16020원
9 : 모순 - 11700원
10 : 빛과 실 - 13500원
11 : 쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션) - 15750원
12 : 듀얼 브레인 - 18900원
13 : 괴수 8호 15 트리플특장판 - 5400원
14 : 길고양이와 늑대 5 더블특전판 - 5400원
15 : 혼모노 - 16200원
16 : 위버멘쉬 - 16020원
17 : 결국 국민이 합니다 - 19800원
18 : 급류 - 12600원
19 : 에그박사 15 - 14220원
20 : 첫 여름, 완주 - 15300원
21 : 친구가 상처 줄 때 똑똑하게 나를 지키는 법 - 15120원
22 : 친구 사이에도 예의가 필요해 - 15300원
23 : 서랍에 저녁을 넣어 두었다 - 10800원
24 : 워런 버핏 웨이 - 29700원

[]

## 2페이지

In [49]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=24'
response = requests.get(url)
#response, response.status_code
#response.content
#response.content.decode('cp949')
#response.text
soup2 = BeautifulSoup(response.text, # response.content
                    'html.parser') #xml이면 xml.parser

In [50]:
# 책제목 2페이지 24개
title2 = soup2.select('a.gd_name')
for t in title2:
    print(t.text, end='\t')

봄의 폭풍과 몬스터 6	흔한남매 19	2025 심우철 실전 동형 모의고사 Season 4	ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC	2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상	엔비디아 젠슨 황, 생각하는 기계	넥서스	스토너	최애의 아이 16 특별판	ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC	2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하	과자 사면 과학 드립니다	하루 한 장 나의 어휘력을 위한 필사 노트	파과 (리커버)	너에게 들려주는 단단한 말	돈의 흐름은 되풀이된다	2025 문동균 한국사 지방직 대비 실전 봉투모의고사	설민석의 한국사 대모험 33	진짜의 마인드	유대인의 상술	최애의 아이 16	질문의 격	2025 선재국어 최우선 실전 봉투 모의고사	작별하지 않는다

In [51]:
# 책가격 2페이지 24개
price2 = soup2.select('strong.txt_num>em.yes_b')
price_num2 = [round(float(p.text.replace(',',''))) for p in price2]

In [52]:
# 가격에 원 붙히기
prices2 = price_num2
prices_with_won2 = list(map(lambda x: str(x) + "원", prices2))
prices_with_won2

['5400원',
 '14220원',
 '12960원',
 '17820원',
 '14850원',
 '25200원',
 '25020원',
 '15120원',
 '35100원',
 '17820원',
 '14400원',
 '13500원',
 '21420원',
 '14220원',
 '16200원',
 '17100원',
 '10800원',
 '12600원',
 '16650원',
 '16920원',
 '7110원',
 '16020원',
 '16200원',
 '15120원']

In [53]:
result2 = []
for idx in range(len(title2)):
    print("{} : {} - {}".format(idx+25,
                                  title2[idx].text,
                                 prices_with_won2[idx],
                                 ))
result2

25 : 봄의 폭풍과 몬스터 6 - 5400원
26 : 흔한남매 19 - 14220원
27 : 2025 심우철 실전 동형 모의고사 Season 4 - 12960원
28 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC - 17820원
29 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상 - 14850원
30 : 엔비디아 젠슨 황, 생각하는 기계 - 25200원
31 : 넥서스 - 25020원
32 : 스토너 - 15120원
33 : 최애의 아이 16 특별판 - 35100원
34 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC - 17820원
35 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하 - 14400원
36 : 과자 사면 과학 드립니다 - 13500원
37 : 하루 한 장 나의 어휘력을 위한 필사 노트 - 21420원
38 : 파과 (리커버) - 14220원
39 : 너에게 들려주는 단단한 말 - 16200원
40 : 돈의 흐름은 되풀이된다 - 17100원
41 : 2025 문동균 한국사 지방직 대비 실전 봉투모의고사 - 10800원
42 : 설민석의 한국사 대모험 33 - 12600원
43 : 진짜의 마인드 - 16650원
44 : 유대인의 상술 - 16920원
45 : 최애의 아이 16 - 7110원
46 : 질문의 격 - 16020원
47 : 2025 선재국어 최우선 실전 봉투 모의고사 - 16200원
48 : 작별하지 않는다 - 15120원

[]

In [54]:
result_append = result.append(result2)
print(result_append)

None

# 50개만 가져오기 (웹크롤링)

In [55]:
# 방법1 requests모듈
import requests
from bs4 import BeautifulSoup
url = 'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=50'
response = requests.get(url)
soup = BeautifulSoup(response.text,
                    'html.parser')

In [65]:
# 책제목 1페이지 50개
titles = [t.text for t in soup.select('a.gd_name')]
print(titles)

['청춘의 독서', '엄마의 말 연습', '어른의 품격을 채우는 100일 필사 노트', '단 한 번의 삶', '이로운 보수 의로운 진보', '소년이 온다', '어른의 행복은 조용하다', '초역 부처의 말', '모순', '빛과 실', '쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션)', '듀얼 브레인', '괴수 8호 15 트리플특장판', '길고양이와 늑대 5 더블특전판', '혼모노', '위버멘쉬', '결국 국민이 합니다', '급류', '에그박사 15', '첫 여름, 완주', '친구가 상처 줄 때 똑똑하게 나를 지키는 법', '친구 사이에도 예의가 필요해', '서랍에 저녁을 넣어 두었다', '워런 버핏 웨이', '봄의 폭풍과 몬스터 6', '흔한남매 19', '2025 심우철 실전 동형 모의고사 Season 4', 'ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC', '2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상', '엔비디아 젠슨 황, 생각하는 기계', '넥서스', '스토너', '최애의 아이 16 특별판', 'ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC', '2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하', '과자 사면 과학 드립니다', '하루 한 장 나의 어휘력을 위한 필사 노트', '파과 (리커버)', '너에게 들려주는 단단한 말', '돈의 흐름은 되풀이된다', '2025 문동균 한국사 지방직 대비 실전 봉투모의고사', '설민석의 한국사 대모험 33', '진짜의 마인드', '유대인의 상술', '최애의 아이 16', '질문의 격', '2025 선재국어 최우선 실전 봉투 모의고사', '작별하지 않는다', '루리 드래곤 3', '2025 써니 행정법총론 봉투모의고사 (4회)']

In [57]:
# 책가격 1페이지 50개
price = soup.select('strong.txt_num>em.yes_b')
price_num = [round(float(p.text.replace(',',''))) for p in price]

In [58]:
# 가격에 원 붙히기
prices = price_num
prices_with_won = list(map(lambda x: str(x) + "원", prices))
prices_with_won

['17010원',
 '15750원',
 '18000원',
 '15120원',
 '18000원',
 '13500원',
 '16020원',
 '16020원',
 '11700원',
 '13500원',
 '15750원',
 '18900원',
 '5400원',
 '5400원',
 '16200원',
 '16020원',
 '19800원',
 '12600원',
 '14220원',
 '15300원',
 '15120원',
 '15300원',
 '10800원',
 '29700원',
 '5400원',
 '14220원',
 '12960원',
 '17820원',
 '14850원',
 '25200원',
 '25020원',
 '15120원',
 '35100원',
 '17820원',
 '14400원',
 '13500원',
 '21420원',
 '14220원',
 '16200원',
 '17100원',
 '10800원',
 '12600원',
 '16650원',
 '16920원',
 '7110원',
 '16020원',
 '16200원',
 '15120원',
 '5400원',
 '7200원']

In [59]:
for idx in range(len(title)):
    print("{} : {} - {}".format(idx+1,
                                  title[idx].text,
                                 prices_with_won[idx],
                                 ))

1 : 청춘의 독서 - 17010원
2 : 엄마의 말 연습 - 15750원
3 : 어른의 품격을 채우는 100일 필사 노트 - 18000원
4 : 단 한 번의 삶 - 15120원
5 : 이로운 보수 의로운 진보 - 18000원
6 : 소년이 온다 - 13500원
7 : 어른의 행복은 조용하다 - 16020원
8 : 초역 부처의 말 - 16020원
9 : 모순 - 11700원
10 : 빛과 실 - 13500원
11 : 쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션) - 15750원
12 : 듀얼 브레인 - 18900원
13 : 괴수 8호 15 트리플특장판 - 5400원
14 : 길고양이와 늑대 5 더블특전판 - 5400원
15 : 혼모노 - 16200원
16 : 위버멘쉬 - 16020원
17 : 결국 국민이 합니다 - 19800원
18 : 급류 - 12600원
19 : 에그박사 15 - 14220원
20 : 첫 여름, 완주 - 15300원
21 : 친구가 상처 줄 때 똑똑하게 나를 지키는 법 - 15120원
22 : 친구 사이에도 예의가 필요해 - 15300원
23 : 서랍에 저녁을 넣어 두었다 - 10800원
24 : 워런 버핏 웨이 - 29700원
25 : 봄의 폭풍과 몬스터 6 - 5400원
26 : 흔한남매 19 - 14220원
27 : 2025 심우철 실전 동형 모의고사 Season 4 - 12960원
28 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC - 17820원
29 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상 - 14850원
30 : 엔비디아 젠슨 황, 생각하는 기계 - 25200원
31 : 넥서스 - 25020원
32 : 스토너 - 15120원
33 : 최애의 아이 16 특별판 - 35100원
34 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC - 17820원
35 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하 - 14400원
36 : 과자 사면 과학 드립니다 - 13500원
37 : 하루 한 장 나의 어휘력을 위한 필사 노트 - 21420원
38 : 파과 (리커버) - 14220원
39 : 너에게 들려주는 단단한 말 - 16200원
40 : 돈의 흐름은 되풀이된다 - 17100원
41 : 2025 문동균 한국사 지방직 대비 실전 봉투모의고사 - 10800원
42 : 설민석의 한국사 대모험 33 - 12600원
43 : 진짜의 마인드 - 16650원
44 : 유대인의 상술 - 16920원
45 : 최애의 아이 16 - 7110원
46 : 질문의 격 - 16020원
47 : 2025 선재국어 최우선 실전 봉투 모의고사 - 16200원
48 : 작별하지 않는다 - 15120원
49 : 루리 드래곤 3 - 5400원
50 : 2025 써니 행정법총론 봉투모의고사 (4회) - 7200원

In [64]:
result = []
for idx in range(len(title)):
    book_title = title[idx].text
    book_price = prices_with_won[idx]
    print(f"{idx+1} : {book_title} - {book_price}")    
    result.append([idx + 1, book_title, book_price])

1 : 청춘의 독서 - 17010원
2 : 엄마의 말 연습 - 15750원
3 : 어른의 품격을 채우는 100일 필사 노트 - 18000원
4 : 단 한 번의 삶 - 15120원
5 : 이로운 보수 의로운 진보 - 18000원
6 : 소년이 온다 - 13500원
7 : 어른의 행복은 조용하다 - 16020원
8 : 초역 부처의 말 - 16020원
9 : 모순 - 11700원
10 : 빛과 실 - 13500원
11 : 쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션) - 15750원
12 : 듀얼 브레인 - 18900원
13 : 괴수 8호 15 트리플특장판 - 5400원
14 : 길고양이와 늑대 5 더블특전판 - 5400원
15 : 혼모노 - 16200원
16 : 위버멘쉬 - 16020원
17 : 결국 국민이 합니다 - 19800원
18 : 급류 - 12600원
19 : 에그박사 15 - 14220원
20 : 첫 여름, 완주 - 15300원
21 : 친구가 상처 줄 때 똑똑하게 나를 지키는 법 - 15120원
22 : 친구 사이에도 예의가 필요해 - 15300원
23 : 서랍에 저녁을 넣어 두었다 - 10800원
24 : 워런 버핏 웨이 - 29700원
25 : 봄의 폭풍과 몬스터 6 - 5400원
26 : 흔한남매 19 - 14220원
27 : 2025 심우철 실전 동형 모의고사 Season 4 - 12960원
28 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC - 17820원
29 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상 - 14850원
30 : 엔비디아 젠슨 황, 생각하는 기계 - 25200원
31 : 넥서스 - 25020원
32 : 스토너 - 15120원
33 : 최애의 아이 16 특별판 - 35100원
34 : ETS 토익 정기시험 기출문제집 1000 Vol. 4 LC - 17820원
35 : 2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하 - 14400원
36 : 과자 사면 과학 드립니다 - 13500원
37 : 하루 한 장 나의 어휘력을 위한 필사 노트 - 21420원
38 : 파과 (리커버) - 14220원
39 : 너에게 들려주는 단단한 말 - 16200원
40 : 돈의 흐름은 되풀이된다 - 17100원
41 : 2025 문동균 한국사 지방직 대비 실전 봉투모의고사 - 10800원
42 : 설민석의 한국사 대모험 33 - 12600원
43 : 진짜의 마인드 - 16650원
44 : 유대인의 상술 - 16920원
45 : 최애의 아이 16 - 7110원
46 : 질문의 격 - 16020원
47 : 2025 선재국어 최우선 실전 봉투 모의고사 - 16200원
48 : 작별하지 않는다 - 15120원
49 : 루리 드래곤 3 - 5400원
50 : 2025 써니 행정법총론 봉투모의고사 (4회) - 7200원

In [63]:
import pandas as pd
df = pd.DataFrame(result, columns=['no', 'title', 'price'])
df.head()

   no                   title   price
0   1                  청춘의 독서  17010원
1   2                엄마의 말 연습  15750원
2   3  어른의 품격을 채우는 100일 필사 노트  18000원
3   4                단 한 번의 삶  15120원
4   5           이로운 보수 의로운 진보  18000원

# 250529 웹크롤링연습

In [5]:
# 방법1
from requests import get
from bs4 import BeautifulSoup

url = 'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=50'
# print(url)
response = get(url)
# response.status_code #200(정상) 상태확인
soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
# soup

<!DOCTYPE html >

<html lang="ko">
<head><link <meta="" content="IE=Edge" href="https://m.yes24.com/Home/Best?DispNo=001" http-equiv="X-UA-Compatible" media="only screen and(max-width: 640px)" rel="alternate"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" http-equiv="Accept-CH"/>
<meta content="86400" http-equiv="Accept-CH-Lifetime"/>
<meta content="unsafe-url" name="referrer"/>
<meta content="width=1170" name="viewport"/>
<title> 국내도서 종합 베스트 - 예스24 </title>
<meta content="예스24" name="title"/>
<meta content="YOUR EVERY STORY 문화 콘텐츠 플랫폼, 예스24" name="description"/>
<meta content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" name="keywords"/>
<link href="//www.yes24.com/OpensearchDescription.xml" rel="search" title="YES24" type="application/opensearchdescription+xml"/>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20220321" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20220321" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/util.js?v=20240626b" type="text/javascript"></script>
<script charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20240321a" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/jqueryExtends.js?v=20240321a" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20250416" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/common/RedirectWebSiteList.min.js?v=20250403" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/common/RedirectWebSite.min.js?v=20250403" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20240222" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20220321" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250403" type="text/javascript"></script>
<link charset="euc-kr" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20211122a" rel="stylesheet" type="text/css">
<link href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20240614" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20250107" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20240920" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20250313" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20240229" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20240222" rel="stylesheet" type="text/css"/>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20240614" />
	<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		// dfinery 디파이너리 위한 설정 값
		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
<script src="https://www.yes24.com/javascript/common.js?v=20250319" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250508" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/clickstream.min.js?v=20211110" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfinery.min.js?v=20240329" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfineryHelper.js?v=20240329" type="text/javascript"></script>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager -->
<script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
<!-- End Google Tag Manager -->
<!-- RTB HOUSE 메인 태깅 코드 -->
<script>
	    (function(w,d,dn,t){w[dn]=w[dn]||[];w[dn].push({eventType:'init',value:t,dc:'asia'});
	    var f=d.getElementsByTagName('script')[0],c=d.createElement('script');c.async=true;
	    c.src='https://tags.creativecdn.com/ld87UMn0bZ6wjXtzlyVc.js';
	    f.parentNode.insertBefore(c,f);})(window,document,'rtbhEvents','ld87UMn0bZ6wjXtzlyVc');
	    (rtbhEvents = window.rtbhEvents || []).push({});
    </script>
<!-- End RTB HOUSE 메인 태깅 코드 -->
<link href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20250317" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?ver=20250519" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/best/best.css?ver=20250116" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20210823" media="all" rel="stylesheet" type="text/css"/></link></head>
<body>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
<dt>콘텐츠 바로가기</dt>
<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>
<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div class="" id="yesWrap">
<div id="yesHeaderArea" style="">
<!-- ########## TOPBANNER 영역 시작 ########## -->
<section>
<div id="upperBnWrap" style="display:none;">
<div id="upperBnRoll">
<div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#befaff"><a href="https://event.yes24.com/detail?eventNo=258862" onclick="setWcode('001');"><img alt="도서앱" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0424_topbn_480x50_L_01.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#ffb3fb"><a href="https://event.yes24.com/present?eventNo=258095" onclick="setWcode('001');"><img alt="트롤리" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0421_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#ffaee5"><a href="https://event.yes24.com/yesBenefit" onclick="setWcode('001');"><img alt="5월혜택" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0502topbn_480x50_L_02.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#ffe97d"><a href="https://event.yes24.com/present?eventNo=258095" onclick="setWcode('001');"><img alt="트롤리" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0421_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#fff7b9"><a href="https://event.yes24.com/detail?eventNo=258281" onclick="setWcode('001');"><img alt="크레마팔레트" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0502topbn_480x50_L_03.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#afc4ff"><a href="https://event.yes24.com/present?eventNo=258095" onclick="setWcode('001');"><img alt="트롤리" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0421_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div>
</div>
<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
</div>
</section>
<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
<!-- ########## TOPBANNER 영역 끝 ########## -->
<!-- ########## HEADER 영역 시작 ########## -->
<div id="yHeader">
<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');"><svg aria-label="YES24" role="img" type="image/svg+xml"><image alt="YES24" height="103" src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/></svg></a></h1>
<div id="yHeaderWrap">
<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
<div class="yHeaderTop">
<h2 class="yBlind">YES24 카테고리 리스트</h2>
<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" title="국내도서"><em class="txt">국내도서</em></a></li><li class="cate002"><a href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" title="외국도서"><em class="txt">외국도서</em></a></li><li class="cate018"><a href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" title="중고샵"><em class="txt">중고샵</em></a></li><li class="cate017"><a href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" title="eBook"><em class="txt">eBook</em></a></li><li class="cateCrC"><a href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" title="크레마클럽"><em class="txt">크레마클럽</em><em class="ico_newSup"></em></a></li><li class="cate003"><a href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" title="CD/LP"><em class="txt">CD/LP</em></a></li><li class="cate004"><a href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" title="DVD/Blu-ray"><em class="txt">DVD/BD</em></a></li><li class="cate006"><a href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" title="GIFT"><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank" title="티켓"><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
<h2 class="yBlind">YES24 유틸메뉴</h2>
<ul class="utilLi">
<li id="LoginText">
<input id="hdfLoginYn" type="hidden" value="N"/>
<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>
</li>
<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>
<li class="myPgGrp">
<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
<dl class="myPgDl">
<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
<dd>
<ul>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
</ul>
</dd>
</dl>
</li>
<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')"><em class="txt">카트</em></a></li>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
</ul>
<dl class="globalYesInfoDl">
<dt><a href="javascript:void(0);"><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
<dd>
<div class="globalYesInfoContArea">
<div class="globalYesInfoCont">
<p class="yesInfo_tit">Global YES24는?</p>
<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
<div class="yesInfo_globalTxt">
<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
<a class="btnC btn_blue" href="https://global.yes24.com" onclick="setWcode('001_016_002')" target="_blank"><span class="bWrap"><em class="txt">English</em></span></a>
<p class="globalTxt_des">
									 作为出售正规 K-POP/K-Drama 相关(CD,图书,DVD) 韩流商品的网站, 支持 中文/英文 等海外结账方式
									</p>
<a class="btnC btn_blue" href="https://cn.yes24.com" onclick="setWcode('001_016_003')" target="_blank"><span class="bWrap"><em class="txt">中文</em></span></a>
<p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
<a class="btnC btn_blue" href="http://ticket.yes24.com/English?Gcode=009_205" onclick="setWcode('001_016_004')" target="_blank"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
</div>
</div>
</div>
</dd>
</dl>
</div>
<!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
<hr/>
<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
<div class="yHeaderMid">
<div class="yesSearch">
<form accept-charset="utf-8" action="//www.yes24.com/product/search?" id="yesSForm" method="get" name="HeadForm" onsubmit="return check_search();">
<input id="keywordAd" name="keywordAd" type="hidden" value=""/>
<input id="keyword" name="keyword" type="hidden"/>
<input id="domain" name="domain" type="hidden" value="ALL"/>
<input id="qdomain" name="qdomain" type="hidden" value="전체"/>
<fieldset>
<legend>검색</legend>
<span class="schIpt">
<label><input accesskey="s" autocomplete="off" class="iptTxt" id="query" maxlength="80" name="query" onblur="blurSearchBar();" onfocus="showLatestSearchList();" onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();" onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" style="ime-mode: active;" title="YES24 검색어 입력" type="text" value=""/></label>
</span>
<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">
<script charset="euc-kr" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" type="text/javascript"></script>
<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>
</div>
<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {
							SearchBarRenderingEnableSet(false);
							if (String($("input#query").val()).length == 0) {
								try{
									srchHistory.show();
								}catch(e){}
								$("#suggestSearchList").hide();
								$("#searchKeyLayer").show();
								$("#latestSearchList").show();
							} else {
								BulletSearchRenewal.InitBulletSearch();
								showSuggestSearchList();
							}
						}

						//검색창 포커스 아웃
						function blurSearchBar() {
							var queryValue = $("#query").val();

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

size = 50
pages = 3
items_list = []

for page in range(1, pages+1):
    url = f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize={size}'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    # 크롤링 대상
    rank = soup.select('em.ico.rank')
    gd_img = soup.select('em.img_bdr > img.lazy')
    gd_name = soup.select('a.gd_name')    
    gd_nameE = soup.select('span.gd_nameE')
    writer = soup.select('span.authPub.info_auth > a')
    price = soup.select('strong.txt_num > em.yes_b')
    grade = soup.select('span.rating_grade > em.yes_b')

    # 책 개수만큼 반복 (보통 gd_name 기준)
    for i in range(len(gd_name)):
        items_list.append({
            'rank': rank[i].text.strip() if i < len(rank) else '',
            'title': gd_name[i].text.strip() if i < len(gd_name) else '',
            'subtitle': gd_nameE[i].text.strip() if i < len(gd_nameE) else '',
            'writer': writer[i].text.strip() if i < len(writer) else '',
            'price': price[i].text.strip() if i < len(price) else '',
            'grade': grade[i].text.strip() if i < len(grade) else '',
            'image': gd_img[i].get('data-original') if i < len(gd_img) and gd_img[i].has_attr('data-original') else '',
#             'link': gd_name[i].get('href') if i < len(gd_name) else ''
        })

# pandas DataFrame으로 변환
df = pd.DataFrame(items_list, columns=['rank', 'title', 'subtitle', 'writer', 'price', 'grade', 'image',]) #'link'

# 결과 출력
df

,rank,title,subtitle,writer,price,grade,image
0,1,청춘의 독서,세상을 바꾼 위험하고 위대한 생각들,유시민,"17,010",9.5,https://image.yes24.com/goods/145629000/L
1,2,엄마의 말 연습,화내지 않고 사랑하는 마음을 오롯이 전하는 39가지 존중어 수업,윤지영,"15,750",9.8,https://image.yes24.com/goods/112925092/L
2,3,단 한 번의 삶,최강 형제가 들려주는 최소한의 정치 교양,김영하,"15,120",9.1,https://image.yes24.com/goods/144021119/L
3,4,어른의 품격을 채우는 100일 필사 노트,양귀자 장편소설,김종원,"18,000",9.8,https://image.yes24.com/goods/142687238/L
4,5,이로운 보수 의로운 진보,AI 시대의 실용적 생존 가이드,최강욱,"18,000",9.6,https://image.yes24.com/goods/145655960/L
...,...,...,...,...,...,...,...
145,146,장돌이네 떡집,,노인경,"11,700",10.0,https://image.yes24.com/goods/145417166/L
146,147,데미안,,심우철,"7,200",10.0,https://image.yes24.com/goods/176787/L
147,148,죽이고 싶은 아이,,박준철,"11,250",,https://image.yes24.com/goods/101864763/L
148,149,회복탄력성의 뇌과학,,크리스틴 로젠,"17,910",,https://image.yes24.com/goods/146524929/L
149,150,평생 투자자,,이영래,"19,800",,https://image.yes24.com/goods/145392475/L

In [11]:
df.to_csv('yes24_bestsellers.csv', index=False, encoding='cp949')

In [ ]:
import pandas as pd

file_path = 'yes24_bestsellers.csv'

with open(file_path, 'r', encoding='utf-8') as f:
    df = pd.read_csv(f)

print(df.head())  # 앞부분만 출력